
@startuml

!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SDRTN®" as API

end box

USR -> APP: Open App
APP -> APP: Initiate the Agora engine
group Join a channel
USR -> APP: Start live streaming
APP -> API: Set the user role as host
APP -> API: Join a channel as host
APP -> API: Publish local media to the channel
end

group Channel media relay
USR -> APP: Start multi-channel live streaming
APP -> APP: Set the source channel info: \nSource channel name, token, and uid
APP -> APP: Set the destination channel info: \n Destination channel name, token, and uid
APP -> API: Call the method to \nstart media relaying
API -> API: Relay stream to the\n destination channel
API -> APP: Report the media relaying\n state with a callback functions
end

group Join multiple channels
USR -> APP: Start multi-channel live streaming
APP -> APP: Create a new channel
APP -> APP: Set the user role as host\n for the new channel 
APP -> API: Join the new channel
API -> APP: Join accepted
APP -> API: Publish to the new channel
end

USR -> APP: Leave the live streaming event
APP -> API: Stop media relaying
APP -> API: Leave all the channels

@enduml