@startuml
!include agora_skin.iuml
autonumber

actor "User" as USR
actor "Admin" as ADM
actor "Owner" as OWN

boundary "Internet" as INT

box "Agora"

participant "Agora Platform" as AP



end box

USR -> AP : Log in to a chat session:\n ""login("John","Imagine",new CallBack(){...})""

group Lifecycle
  USR -> AP: Open a new group:\n ""createGroup("Quarrymen", "Rock'n'roll", null , "Wanna hold my hand?", null)""
  activate AP
  note over OWN: The creator is automatically the group owner
  
  OWN <-> AP: Update the group name:\n""changeGroupName("qu4rrym3n","Beatles")""

    group Group membership
        OWN <-> AP: Invite users to join the group: \n""            String[] newMembers = {"Paul","George", "Stuart", "Pete"};"" \n""addUsersToGroup("qu4rrym3n", newMembers)""
        OWN <-> AP: Block someone from the group: \nblockUser("qu4rrym3n","Stuart")
        OWN <-> AP: Remove someone from the group: \n""removeUserFromGroup("qu4rrym3n","Pete")""
        OWN <-> AP: Add new users to the group: \n            ""String[] newMembers = {"Ringo"};"" \n""addUsersToGroup("qu4rrym3n", newMembers)""
    end

    group Manage user roles
      OWN -> AP: Promote a member to admin:\n ""addGroupAdmin("qu4rrym3n","Paul")""
    end

    group Announcements
        ADM <-> AP: Message the group: ""updateGroupAnnouncement("qu4rrym3n","I am the Walrus")""
    end

    group Mute
                  ADM <-> AP: Stop members of the group participating in a conversation:\n""List<String> hush = new ArrayList<>(List.of("George", "Ringo"));"" \n""muteGroupMembers("qu4rrym3n", hush, 10);""
    end

  OWN <-> AP-- : Close the group: \ndestroyGroup("qu4rrym3n")
  deactivate AP
end

USR -> AP : Log out of the chat session:\n ""logout(true);""

@enduml