
@startuml

!include ../images/agora_skin.iuml

Actor "Product Owner" as PO
Actor "Project Manager" as PM
Actor "Technical Writer" as TW
Actor "Tester" as QA
Actor "DevReller" as DR

PO -> PM: Request documentation for new features\n Or update existing docs
PO -> DR: Inform DevRel about new features

Group Feature implementation
    PM -> PM: Create Gitlab milestone for the feature.
    PM -> PM: Create Gitlab issue for each platform that needs individual\n implementation details, then assign tasks to writers.
    Loop For each issue

        note right of PO
         Implementation and documentation tasks completed in parallel
        end note
            TW -> TW: Create milestone branch
            loop Validate
            TW -> TW: Write bare-bones code that runs in the get-started app.
            TW -> TW: In issue branch, document why and how to implement \nthe feature.
            TW -> QA: Request documentation validation in merge request to\n milestone branch
            QA -> QA: Validate documentation and test the code in the document
            QA <-> TW: If necessary: request changes, update, validate
            QA -> TW: Documentation approved
            TW -> TW: Merge branch, close issue.
            end loop
    end loop
    TW -> TW: Create merge request from milestone branch to \nversion branch

    PM -> DR: Request documentation validation for milestone
    DR -> DR: Validate documentation and test the code in the documents
    DR <-> TW: If necessary: request changes, update, validate
    DR -> TW: Documentation approved
    TW -> TW: Merge milestone branch, close milestone.
end
PM -> PO: HLD implementation complete
@enduml



