@startuml

actor User

participant "Your app server" as LocalService

participant "Agora token builder" as AgoraTool

participant "Agora Chat server" as AgoraChatService

User->LocalService : 1. Request to get a user token

LocalService->AgoraTool : 2. Generate an Agora app token
AgoraTool-->LocalService : Return Agora app token

LocalService->AgoraChatService : 3. Convert Agora app token to Agora Chat app token
AgoraChatService-->LocalService : Return Agora Chat app token

LocalService->AgoraChatService : 4. Use Agora Chat app token to get Agora Chat user UUID
AgoraChatService-->LocalService : Return Agora Chat user UUID or null

group if returns null
LocalService->AgoraChatService : 5. Use Agora Chat app token to create an Agora Chat user
AgoraChatService-->LocalService : Return Agora Chat user UUID
end

LocalService->AgoraTool : 6. Generate Agora Chat user token
AgoraTool-->LocalService : Return Agora Chat user token

LocalService-->User : 7. Response Agora Chat user token

@enduml
