@startuml
!include agora_skin.iuml


actor "User" as USR

boundary "Internet" as INT

box "Agora customer"
participant "Agora Web Client" as AC

end box

boundary "Agora" as AGORA

box "Agora"
participant "Agora Platform" as AP
end box

USR -> AC: Login to Agora Client

AC -> AP: Retrieve room name\n and token

AC -> AP: Request to join room
AP -> AP: Authenticate

AP -> AC: Room joined

AC -> AC: Interact with colleages

AC -> AP: Request to leave room

AP -> AC: Room left


@enduml