@startuml media-stream-encryption
!include agora_skin.iuml

actor "User" as USR

box "Implemented by you"
participant "App" as APP
participant "Developer's \nAuthentication System" as SVR
end box

box "Provided by Agora"
participant "API" as API
end box

USR -> APP: Start the app
APP -> APP: Initiate the Video SDK engine

group Media stream encryption
APP -> SVR: Login to the developer's \nauthentication system.
APP -> SVR: Request a 32-byte key
SVR -> SVR: Generate a 32-byte\n string using OpenSSL
SVR -> APP: Requested key
APP -> SVR: Request a 32-byte salt in \nBase64 format
SVR -> SVR: Generate a 32-byte\n string in Base64 \nformat using OpenSSL
SVR -> APP: Requested salt
APP -> APP: Create a encryption configuration using \nthe received salt and key 
APP -> API: Call the method to set the \nencryption configuration
end

USR -> APP: Select a channel to join
APP -> API: Join a channel with user Id, channel name, and token
API -> APP: Join accepted
APP <-> API: Encrypted media stream


@enduml
