@startuml 
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Video SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

USR -> APP: Open App
APP -> APP: Use Video SDK to create an instance of Agora Engine
APP -> APP: Enable audio and video in the engine

group Join
USR -> APP: Join a channel
APP -> APP: Retrieve authentication token to join a channel
APP -> API: Join the channel 
end

group Play media files
USR -> APP: Select media file
APP -> APP: Use Video SDK to create an instance of Media Player
APP -> API: Open media file using Media Player
API -> APP: Open media file completed
USR -> APP: Play media file
APP -> APP: Set up local video panel \nto display Media Player output
APP -> API: Update channel media options \nto publish Media Player output
APP -> API: Play the media file on the Media Player
USR -> APP: Pause or resume play
APP -> API: Call pause or resume methods
API -> APP: Media file played completely
APP -> API: Resume publishing of camera and microphone
end

@enduml
