@startuml
!include agora_skin.iuml


actor "User" as USR

boundary "Internet" as INT

box "Agora customer"
participant "Agora Web Client" as AC
participant "Security Infrastructure" as ATS
participant "Mobile device" as MD

end box

boundary "Agora" as AGORA

box "Agora"
participant "Agora Platform" as AP
end box

USR -> AC: Login to Agora Client
AC -> ATS : Login to your \n security infrastructure
ATS -> ATS : Authenticate user
ATS -> AC: return AccessToken

AC -> AP: apiCallToLoginToAgoraPlatform
AP -> AP: Authenticate AccessToken
AP-> AC: Login authorized

USR -> AC: Tap secure channel
AC -> ATS: Call to step-up webhook
ATS -> MD: Send SMS
MD -> USR: SMS notification \n with security code
USR -> AC: Enter security code
AC -> ATS: Send security code
ATS -> ATS: Authenticate
ATS -> AP: apiCallToJoinSecureChannel
AP -> AP: Join user to secure channel
AP <-> AC: Stream channel
AC <-> USR: Join secure channel
@enduml