@startuml
!include agora_skin.iuml
autonumber

actor "User" as USR

boundary "Internet" as INT

box "Agora customer"
participant "Agora Client" as CAC
participant "Your backend" as CB
participant "Cloud storage" as CCS

end box

boundary "Agora" as AGORA

box "Agora"
participant "Agora Platform" as AP
participant "Agora cloud storage" as ACS
end box

USR -> CAC: Follow upload\nwizard in client
note left: User is already\nlogged into Agora

CAC -> CB: Upload file and\n request file conversion
CB -> CCS: Upload to \n cloud storage
CCS -> CB: Return URL to\n uploaded file

CB -> AP: Request file conversion: \n//POST /v5/services/conversion/tasks//
AP -> CB: conversion ""task uuid""

group While poll for progress: //GET /v5/services/conversion/tasks/""<task uuid>""?type=static//
CB -[hidden]> AP:
AP <-> CCS: Retrieve uploaded file
AP -> AP: Convert
AP -> ACS: Upload to \n cloud storage
AP -> CB: Return  URL to\n converted files
end


CB -> CAC: Send JSON containing \nURLS to converted files
CAC -> CAC: Insert converted images \ninto current whiteboard
CAC -> USR: Display upldated\n whiteboard
@enduml