@startuml 
!include ../video-sdk/agora_skin.iuml
skinparam SequenceGroupBodyBackgroundColor transparent

actor "User" as USR

box "Your app"
participant "IoT SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

group Set up Agora engine
APP -> APP: Instantiate the Agora engine
APP -> APP: Set engine options
APP -> API: Verify license and initialize the engine
APP -> API: Create a connection
end

group Join a channel
USR -> APP: Join a channel
APP -> API: Call the method to join a channel
APP <- API: On join channel success callback
end

group Send audio and video
APP -> API: Start thread to send audio data
APP -> API: Start thread to send video data
end

group Receive audio and video
APP <- API: On audio data callback
APP -> USR: Render audio frame
APP <- API: On video data callback
APP -> USR: Render video frame
end

group Leave channel
USR -> APP: Leave channel
APP -> API: Call the leave channel method
end

group Clean up
APP -> API: Destroy the connection
APP -> API: Call the finish method to release resources
end

@enduml
