@startuml 
!include ../video-sdk/agora_skin.iuml
skinparam SequenceGroupBodyBackgroundColor transparent

actor "User" as USR

box "Your app"
participant "IoT SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

group Setup Agora engine
APP -> APP: Instantiate the Agora RTC engine
APP -> APP: Set options including\n log file path and logging level
APP -> API: Verify license and initialize the engine
APP -> API: Create a connection
end

group Join a channel
USR -> APP: Join a channel
APP -> API: Set bandwidth estimation parameters
APP -> APP: Specify the audio codec, sampling rate,\n and the number of channels
APP -> API: Call the join channel method
APP <- API: on join channel success callback
end

group Send and receive audio and video
APP -> API: Start threads to send audio and video data
APP <- API: Receive audio and video data
APP -> USR: Render audio and video frames
end

group Detect and respond to network bandwidth changes
API -> APP: On target bitrate changed callback
APP -> APP: Adjust the sending bit rate and resolution
API -> APP: On key frame generation request callback
APP -> API: Send a key frame
end

group Manage audio and video streams
USR -> APP: Mute local audio or video
APP -> API: Call mute local audio or \n mute local video
USR -> APP: Mute remote audio or video
APP -> API: Call mute remote audio or \n mute remote video
APP <- API: On user mute audio callback
APP -> APP: Suspend or resume audio feed
APP <- API: On user mute video callback
APP -> APP: Suspend or resume video feed
end

@enduml
