@startuml

start
:Receive the activated\nlicenses from the server;
repeat
  :Write license to device;
  :Device reads license;
repeat while (Read result) is (Failure)
->Success;
:Pass the license to the SDK;
stop

@enduml
