@startuml 
!include ../video-sdk/agora_skin.iuml

actor "You" as USR

box "Your IoT device"
participant "IoT SDK" as APP
end box

box "Agora"
participant "Agora Sales" as SAL
participant "REST API" as API
end box

USR -> SAL: Contact Agora sales to request a license
USR <- SAL: Send license information
USR -> API: Activate the license
USR <- API: Send activation info
USR -> APP: Write a license to the device


@enduml
