@startuml send-and-receive-media-streams

!include agora_skin.iuml
 
box "Your app"
participant "<size:40><&layers>\nSDK" as APP
end box

box "Agora"
participant "<size:40><&cloud>\nSD-RTN" as API
end box

APP -> APP: Create SDK engine instance
APP -> API: Initialize SDK
APP -> APP: Create connection object
APP -> API: Register a connection event observer
APP -> API: Connect to Agora service
API -> APP: Connection established

group Send media streams
APP -> APP: Create media sender objects
APP -> APP: Create audio and video tracks
APP -> APP: Enable media tracks
APP -> API: Publish media tracks
end

group Receive media streams
APP -> API: Register media frame observers
API -> APP: Receive media streams
end

group Stop sending and receiving media streams
APP -> API: Stop publishing media streams
APP -> APP: Disable media capture
APP -> API: Unregister media observers
end

group Disconnect
APP -> API: Disconnect from Agora service
APP -> APP: Release all resources
end

@enduml
