
scale max 1000 width
skinparam linetype ortho
hide stereotype

skinparam backgroundColor #00000000
skinparam Shadowing false
skinparam BoundaryBackgroundColor #00000000
skinparam BoundaryBorderColor #0a9efdff
skinparam DiagramBorderColor #0a9efdff
skinparam defaultTextAlignment center
skinparam SequenceMessageAlign center
skinparam ReferenceBorderThickness 2


skinparam sequence {

'Users and boundries (DBS for example)
    ActorBorderThickness 3
   	ActorBorderColor #0a9efdff
	ActorBackgroundColor #00000000
	ActorFontColor #0a9efdff
	ActorFontName Arial
    ActorFontStyle regular
    ActorFontSize 14

    AgentBackgroundColor #00000000

'Arrows
   	ArrowFontColor #0a9efdff
   	ArrowFontSize 14
   	ArrowFontStyle regular
    ArrowColor #ee4c14
    ArrowThickness 2fs

    RectangleBorderThickness 3
    BoxBackgroundColor #99999955
    BoxBorderColor #0a9efdff

'Capability
   	BoxFontColor #0a9efdff
   	BoxFontName Arial
   	BoxFontStyle regular
   	BoxFontSize 16

    BoundaryBackgroundColor #0a9efdff
    BoundaryBorderColor #0a9efdff
    BoundaryFontColor #0a9efdff
    BoundryFontName Arial
    BoundaryStereotypeFontColor #0a9efdff

    ClassBorderColor #0a9efdff
    ComponentBorderColor #0a9efdff

    DividerBackgroundColor #00000000
    DividerBorderColor #0a9efdff
    DividerBorderThickness 3
    DividerFontColor #0a9efdff
    DividerFontName Arial
    DividerFontSize regular
    DividerFontStyle 14

' Loops but not the title text
    GroupBorderColor #0a9efdff
    GroupBodyBackgroundColor #0a9efd11
    GroupHeaderBackgroundColor #0a9efd11
    GroupBorderThickness 2
    GroupFontName Arial
    GroupFontSize 13
    GroupFontColor #0a9efdff
'Title text for loops
    GroupHeaderFontColor #000000
    GroupHeaderFontName Arial
    GroupHeaderFontSize 13
    GroupHeaderFontStyle regular

   	LifeLineBorderColor #0a9efdff
   	LifeLineBackgroundColor #0a9efdff
   	LifeLineFontColor  #0a9efdff

'Services
   	ParticipantBorderColor #0a9efdff
   	ParticipantBackgroundColor #00000000
   	ParticipantFontSize 14
   	ParticipantFontStyle regular
   	ParticipantFontName Arial
   	ParticipantFontColor #0a9efdff
    ParticipantBorderThickness 2

    ReferenceBorderThickness 2


'   SwimlaneBorderThickness 2

    TitleFontColor #0a9efdff
    TitleFontName Arial
    TitleFontSize 18
    TitleBorderThickness 5

}
skinparam interface {
  BackgroundColor #00000000
  BorderColor #0a9efdff
  BorderThickness 1
  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regulars

}


skinparam usecase {
  BackgroundColor #00000000
  BorderColor #ee4c14
  BorderThickness 1
  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

}

skinparam note {

  BackgroundColor #00000000

  BorderColor #0a9efdff
  BorderThickness 1

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

}

skinparam activity {

  BackgroundColor #00000000
  DiamondBackgroundColor #00000000
  DiamondBorderColor #0a9efdff
  BorderColor #0a9efdff
  BorderThickness 4
  DiamondBackgroundColor #00000000
  DiamondBorderColor #0a9efdff
  DiamondFontColor #0a9efdff
  activityDiamondFontName Arial
  activityDiamondFontSize 13
  DiamondFontStyle regular
  StartColor #0a9efdff
  StopColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

}

skinparam card {
  BackgroundColor #00000000
  BorderColor #00000000
  BorderThickness 0
  FontColor #00000000
}


skinparam rectangle {

  BackgroundColor #00000000

  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

  shadowing true
}

skinparam agent {

  BackgroundColor #00000000
  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

  shadowing true
}

skinparam folder {

  BackgroundColor #00000000

  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

  shadowing true
}

skinparam file {

  BackgroundColor #00000000

  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

  shadowing true
}

skinparam cloud {

  BackgroundColor #00000000

  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

}

skinparam class {

  BackgroundColor #00000000

  BorderColor #0a9efdff
  BorderThickness 1

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular



}

'For services
skinparam component {

  BackgroundColor  #00000000

  BorderColor #0a9efdff
  BorderThickness 2

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular
}



'databases
skinparam database {

  BackgroundColor #88888855

  BorderColor #0a9efdff
  BorderThickness 2

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

}


'For Capabilities
skinparam frame {

  ArrowColor #0a9efdff

  BackgroundColor #00000000
  BorderColor #0a9efdff
  BorderThickness 4

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular
}


' External systems in architecture diagrams
skinparam node {

  ArrowColor #0a9efdff

  BorderThickness 2
  BackgroundColor #00000000
  BorderColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

}

skinparam package {
  BorderThickness 2
  BackgroundColor #00000000
  BorderColor #0a9efdff

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

}

' Activity diagrams, for different capabilities

skinparam partition {

  BackgroundColor #88888855

  BorderColor #0a9efdff
  BorderThickness 2

  FontColor #0a9efdff
  FontName Arial
  FontSize 13
  FontStyle regular

}

skinparam ArrowFontColor #0a9efdff
skinparam ArrowFontSize 13
skinparam ArrowFontStyle regular
skinparam ArrowColor #0a9efdff
skinparam ArrowThickness 2
skinparam ArrowFontName Arial

skinparam linetype ortho
hide stereotype

!definelong AWSEntityColoring(e_stereo)

skinparam rectangle<<e_stereo>> {
    BackgroundColor AWS_BG_COLOR
    BorderColor orange
    Shadowing true
}
!enddefinelong

!definelong AWSEntity(e_alias, e_label, e_techn, e_color, e_sprite, e_stereo)
rectangle "<color:e_color><$e_sprite></color>\n\n==e_label" <<e_stereo>> as e_alias
!enddefinelong

!definelong AWSEntity(e_alias, e_label, e_techn, e_descr, e_color, e_sprite, e_stereo)
rectangle "<color:e_color><$e_sprite></color>\n\n==e_label" <<e_stereo>> as e_alias
!enddefinelong
