@startuml geofencing
!include ../video-sdk/agora_skin.iuml

box "Implemented by you"
participant "App client" as APP
participant "Server" as SERVER
end box

box "Provided by Agora"
participant "Classroom SDK" as FCRSDK
participant "Flexible Classroom Server" as FCRSERVER
end box

APP -> SERVER: Apply for token
SERVER -> APP: Generate and return token
APP -> FCRSDK: Log into Flexible Classroom with user ID and token
FCRSDK -> FCRSERVER: Verify token
FCRSERVER -> APP: Successful login callback

@enduml
