@startuml geofencing
!include agora_skin.iuml

box "User"
participant "<size:40><&person>" as USR
end box

box "App"
participant "<size:40><&tablet>" as APP
end box

box "Agora SD-RTN"
participant "<size:40><&cloud>" as RTN
end box

USR -> APP: Start the app

group Restrict area access
APP -> APP: Set SD-RTN region in the Agora\n engine configuration
APP -> APP: Initiate the Agora engine
APP -> RTN: Connect to SD-RTN in a\n specific region
RTN -> APP: Success response
end

USR -> APP: Select a channel to join
APP -> RTN: Join a channel with user \nId, channel name, and token
RTN -> APP: Join accepted

@enduml
