@startuml 
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Voice SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

USR -> APP: Open App

group Set log file configuration and create engine
APP -> APP: Set log file parameters
APP -> APP: Use Voice SK to create an instance of Agora Engine
end

group Pre-call tests
USR -> APP: Start the echo test
APP -> API: Call the method to start the echo test
APP <-> API: Send and receive back\n audio after a delay\n to test hardware and network quality
APP -> APP: Start the network probe test
APP -> API: Call the method to start the network probe test
API -> APP: Deliver network quality score\n and network statistics
end

group Set the audio profile
APP -> APP: Specify audio profile and scenario\n based on the nature of the app
APP -> API: Call the method to set\n the audio profile and scenario
end

USR -> APP: Join channel
APP -> API: Join channel

group Monitor in-call quality
APP -> APP: Enable the quality statistics
API -> APP: Recieve network, call, and audio quality statistics
API -> APP: Recieve state change notifications
APP -> USR: Notify the user
APP -> API: Take corrective action
end

group Echo cancellation
USR -> APP: Choose the audio file to be played\n and specify mixing options
APP -> API: Call the method to \nstart audio mixing
API -> APP: Uses echo-cancellation \nfeatures to remove echo
end

@enduml