@startuml geofencing
!include agora_skin.iuml

actor "User" as USR

box "Implemented by you"
participant "App" as APP
end box

box "Provided by Agora"
participant "SD-RTN" as API
end box

USR -> APP: Start the app

group Geofencing
APP -> APP: Set SD-RTN region in the Agora\n engine configuration
APP -> APP: Initiate the Agora engine
APP -> API: Connect to SD-RTN in a\n specific region
API -> APP: Success response
end

USR -> APP: Select a channel to join
APP -> API: Join a channel with user \nId, channel name, and token
API -> APP: Join accepted

@enduml
