@startuml
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Voice SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

USR -> APP: Open App
APP -> APP: Use Voice SDK to create an Agora Engine instance
APP -> APP: Create and play the local audio track
APP -> APP: Bypass autoplay block when \n onAutoplayFailed event occurs

group Join
USR -> APP: Join a channel
APP->APP: Retrieve authentication token to join a channel
APP -> API: Join the channel 
end

group Publish and Subscribe
APP -> API: Publish the microphone track to the channel
API -> APP: Subscribe to tracks from other users
APP -> API: Manage local and remote audio tracks 
end

group Common workflows
APP -> APP: Bypass autoplay blocking
APP -> API: Unpublish the local audio track
USR -> APP: Adjust volume
APP -> API: Call API methods to adjust or mute \n the local or remote audio track
USR -> APP: Mute/Unmute audio
APP -> API: Call the API method to mute or unmute \n the local audio track
end

USR -> APP: Leave the channel
APP -> API: Leave the channel

@enduml
