@startuml

!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Voice SDK" as APP
end box

box "Agora"
participant "SD-RTN" as API
end box

USR -> APP: Open App
APP -> APP: Initiate the Agora Voice SDK engine: \n agoraEngine = RtcEngine.create

group User
USR -> APP: Join a call
APP -> APP: Retrieve authentication token to join channel
APP -> API: Join the channel:\n agoraEngine.joinChannel()
APP <- API: Remote user joined:\n onUserJoined()
end

USR -> APP: Leave the call
APP -> API: Leave the channel: \n agoraEngine.leaveChannel()

USR -> APP: Close app
APP -> APP: Clean up local resources: \n  agoraEngine.destroy()


@enduml

