@startuml
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Voice SDK" as APP

end box

box "Agora"

participant "SDRTN®" as API

end box

USR -> APP: Open App
APP -> APP: Create an instance of the Voice SDK engine:\n agoraEngine = agoraEngine.createAgoraRtcEngine
APP -> APP: Initialize the created instance: \n agoraEngine.initialize

group User
USR -> APP: Start call
APP->APP: Retrieve authentication token to join channel
APP -> API: Join a channel:\n agoraEngine.joinChannel
API -> APP : Join accepted
API <-> APP: Receive and send audio stream
end
USR -> APP: Leave call
APP -> API: leave the channel:\n agoraEngine.leaveChannel

@enduml
