@startuml

' Import sequence diagram skin
!include agora_skin.iuml

' Create participants
box #E6F9FF
participant "<$app> App: Broadcaster" as app1
end box
box #F1F7FF
participant "<$sdk> Video SDK" as sdk
end box
box #FFF7E7
participant "<$app-yellow> App: Audience" as app2
end box

' Title (optional)
app1 -> sdk: Register raw video data observer and callback
app2 -> sdk: Register raw video data observer and callback

alt #ECFDF3 \nOption 1
   sdk -->> app1: Retrieve and process video data after capture
else #FEF3F2 Option 2
   sdk -->> app1: Retrieve video data before local encoding
else #FFF7E7 Option 3
   sdk -->> app2: Retrieve remote video data before local rendering
end

@enduml
