@startuml 
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "RTC SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

USR -> APP: Open App
APP -> APP: Create an instance of the RTC SDK engine
APP -> APP: Enable audio and video in the engine

group Setup external source
APP -> APP: Check the external source for compatibility
APP -> API: Set external video or audio source
end

group Join
USR -> APP: Join a channel
APP -> APP: Retrieve authentication token to join a channel
APP -> API: Join the channel 
end

group Process data
APP -> APP: Manage capturing and processing \nusing external methods
end

group Stream data
APP -> API: Push external video or audio frame
end

USR -> APP: Leave the channel
APP -> API: Leave the channel

@enduml
