@startuml
!include agora_skin.iuml

box "App"
participant "<size:40><&tablet>" as APP
end box

box "SDK"
participant "<size:40><&layers>" as SDK
end box

box "Agora SD-RTN"
participant "<size:40><&cloud>" as RTN
end box

APP->SDK: Create and initialize the engine
APP->SDK: Set up the external video source

group Join channels
APP->SDK: Join channel(s)
SDK->RTN: Request to join channel(s)
end

group Push video frames
APP->APP: Load the video data from the \nlocal video file into video frames
APP->SDK: Triggers a thread to push video frames
SDK->RTN: Push video frames to SDK
end

APP->SDK: Terminate the thread that pushes video frames

APP->SDK: Leave channel(s)
SDK->RTN: Request to leave channel(s)
APP->SDK: Destroy the engine

@enduml
