@startuml
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Video SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

USR -> APP: Open App

group Create Agora engine 
APP -> APP: Set log file path, log level and file size
APP -> APP: Create Agora Engine
end

group Best practice for app initiation
APP -> API: Enable dual-stream mode\n to allow remote users to choose a stream type
APP -> API: Set local publish and remote subscribe fallback options
end

group Settings check
APP -> API: Specify audio profile and scenario\n based on the nature of the app
APP -> API: Set video encoder configuration
APP -> API: Call the method to start the network probe test
API -> APP: Deliver network quality score\n and network statistics
end

USR -> APP: Join channel
APP -> APP: Enable video
APP -> API: Join channel

group In-call quality monitoring
APP -> APP: Enable the quality statistics
API -> APP: Receive network, call, audio and video quality statistics
API -> APP: Receive state change notifications
APP -> USR: Notify the user
APP -> API: Take corrective action
end

@enduml