@startuml
!include agora_skin.iuml

actor "User" as USR

box "Implemented by you"
participant "App" as APP
participant "Developer's \nAuthentication \nSystem" as SVR
end box

box "Provided by \nAgora"
participant "SDRTN®" as API
end box

group Join a Channel with Authentication
USR -> APP: Start the app
APP -> SVR: Login to your \nidentity management system.
USR -> APP: Select a channel
APP -> SVR: Request an Agora authentication token using \nchannel name, role, token type and user Id
SVR -> SVR: Validate user request \nagainst internal security
SVR -> SVR: Use integrated Agora library\n to generate a token 
APP <- SVR: Return the token to the client

APP -> API: Join a channel with user Id, channel name, and token
API -> API: Validate \nthe token
API -> APP: Trigger the callback after adding user to the channel
end

@enduml
