@startuml 
!include agora_skin.iuml

actor "User" as USR

box "RTC SDK"
participant "<size:40><&layers>" as APP
end box

box "Agora SDRTN®"
participant "<size:40><&cloud>" as RTN
end box

USR -> APP: Open App
APP -> APP: Use RTC SDK to create an instance of Agora Engine
APP -> APP: Enable audio and video in the engine

group Join
USR -> APP: Join a channel
APP -> APP: Retrieve authentication token to join a channel
APP -> RTN: Join the channel 
end

group Play media files
USR -> APP: Select media file
APP -> APP: Use RTC SDK to create an instance of Media Player
APP -> RTN: Open media file using Media Player
RTN --> APP: Open media file completed
USR -> APP: Play media file
APP -> APP: Set up local video panel \nto display Media Player output
APP -> RTN: Update channel media options \nto publish Media Player output
APP -> RTN: Play the media file on the Media Player
USR -> APP: Pause or resume play
APP -> RTN: Call pause or resume methods
RTN --> APP: Media file played completely
APP -> RTN: Resume publishing of camera and microphone
end

@enduml
