@startuml 
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "RTC SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

group Set up the music content center
APP -> APP: Load the DRM extension framework.
APP -> APP: Create an instance of the music content center.
APP -> API: Initialize the music content center.
end

group Find music from the content center
USR -> APP: Find music.
APP -> API: Call the method to search for music.
APP <- API: Receive search results through the callback.
APP -> API: Call the method to download music charts.
APP <- API: Receive music charts data through the callback.
end

group Play DRM music
USR -> APP: Press play
APP <-> API: Preload selected music.
APP -> APP: Create an instance of music player.
APP <-> API: Open and play music files.
end


@enduml
