@startuml
!include agora_skin.iuml

box "App"
participant "<size:40><&tablet>" as APP
end box

box "SDK"
participant "<size:40><&layers>" as SDK
end box

box "Agora\nSDRTN®"
participant "<size:40><&cloud>" as RTN
end box

APP->SDK: AgoraRTC.createClient
note left: Create two clients:\n uplinkClient and downlinkClient
APP->SDK: uplinkClient.join
SDK->RTN: Join channel request
APP->SDK: downlinkClient.join
SDK->RTN: Join channel request

group Create and publish local audio and video tracks
APP->SDK: AgoraRTC.createMicrophoneAndCameraTracks
APP->SDK: uplinkClient.publish
SDK->RTN: Send audio and video data
end

group Subscribe to audio and video tracks
RTN-->APP: downlinkClient.on("user-published")
APP->SDK: downlinkClient.subscribe
RTN-->SDK: Receive audio and video data
APP->SDK: track.play
end

group Get network data
SDK-->APP: downlinkClient.on("network-quality")
SDK-->APP: uplinkClient.on("network-quality")
APP->SDK: uplinkClient.getLocalAudioStats
APP->SDK: uplinkClient.getLocalVideoStats
APP->SDK: downlinkClient.getRemoteAudioStats
APP->SDK: downlinkClient.getRemoteVideoStats
end
@enduml
