@startuml 
!include agora_skin.iuml

box "App"
participant "<size:40><&tablet>" as APP
end box

box "RTC SDK"
participant "<size:40><&layers>" as SDK
end box

box "Agora SDRTN®"
participant "<size:40><&cloud>" as RTN
end box

group Create a local client
APP->SDK: AgoraRTC.createClient\n Set mode to 'rtc'
end

group Join channel
APP->SDK: AgoraRTCClient.join
SDK->RTN: Join channel request
end

group Create and publish local audio track
APP->SDK: Create local audio track\n AgoraRTC.createMicrophoneAudioTrack
APP->SDK: Publish local audio track\n AgoraRTCClient.publish
SDK->RTN: Send audio data
end

group Subscribe to remote users
APP<--RTN: Remote users publish audio track\n client.on("user-published")
APP->SDK: Get remote user object\n AgoraRTCClient.remoteUsers
APP->SDK: Subscribe to remote user object\n AgoraRTCClient.subscribe
SDK<-RTN: Receive audio data
APP->SDK: Get remote audio object\n AgoraRTCRemoteUser.audioTrack
end

group Leave the channel
APP->SDK: Turn off the local audio track\n MicrophoneAudioTrack.close
APP->SDK: Leave the channel\n AgoraRTCClient.leave
SDK->RTN: Request to leave the channel
end

@enduml
