@startuml

!include agora_skin.iuml

box "App: Host"
participant "<size:40><&tablet>" as HST
end box

box "RTC SDK"
participant "<size:40><&layers>" as SDK
end box

box "App: Audience" 
participant "<size:40><&tablet>" as AUD
end box

group Initialize the engine
HST -> SDK: Create and initialize the engine
AUD -> SDK: Create and initialize the engine
end

group Join channel
HST -> SDK: Join the channel and\n set the user role as host
AUD -> SDK: Join the channel and\n set the user role as audience
SDK --> HST: Notify the host that the channel has been joined
SDK --> AUD: Notify the audience that the channel has been joined
end

group Start audio interaction
AUD <- SDK: Receive audio
HST -> SDK: Send audio
end

group End audio interaction
HST -> SDK: Leave the channel
HST <-- SDK: Notify the host that \nit has left the channel
AUD <-- SDK: Notify the audience that \nthe host has left the channel
AUD -> SDK: Leave the channel
SDK --> AUD: Notify the audience that \nit has left the channel
HST -> SDK: Destroy the engine
AUD -> SDK: Destroy the engine
end

@enduml

