@startuml 
!include agora_skin.iuml

box "App"
participant "<size:40><&tablet>" as APP
end box

box "Video SDK"
participant "<size:40><&layers>" as SDK
end box

box "Agora SDRTN®"
participant "<size:40><&cloud>" as RTN
end box

group Screen sharing
APP->SDK: Get available screen or window information
APP<-SDK: Return available screen or window information
APP->SDK: Start screen capture
APP->SDK: Set the screen sharing scene (optional)
APP->SDK: Join the channel
SDK->RTN: Publish the screen sharing\n stream in the channel
APP->SDK: Update the screen sharing area or parameters
APP->SDK: Display stroke on the shared screen (optional)
APP->SDK: Block window (optional)
SDK->RTN: Publish the updated screen sharing\n stream in the channel
APP->SDK: Stop screen sahring
SDK->RTN: Stop publishing the screen sharing\n stream in the channel
end

@enduml
