@startuml
!include agora_skin.iuml

box "App"
participant "<size:40><&tablet>" as APP
end box

box "Agora\nSDK"
participant "<size:40><&layers>" as SDK
end box

box "Spatial audio\nengine"
participant "<size:40><&map>" as SPAT
end box

group Initialize engine
APP->SDK: Create and initialize Agora engine
APP->SPAT: Create and initialize the spatial audio engine
end

group Set an audio profile and scenario
APP->SDK: Set up an audio profile 
APP->SDK: Set up audio scenario
end

group Join channel
APP->SDK: Join a channel and set channel usage scenarios and user roles
end

group Set an audio reception range
APP->SPAT: Set the maximum number of audio streams to\n receive within the audio receiving range
APP->SPAT: Set the maximum range for receiving audio
end

group Update spatial position
APP->SPAT: Update the spatial position of the local user
APP->SPAT: Update the spatial position of\n the remote user or media player
end

group Set up spatial audio effects
APP->SDK: Set the spatial audio parameters of\n the remote user or media player locally
APP->SDK: Set up a sound insulation area (Optional)

group Set the headphone equalization effect (Optional)
APP->SPAT: Use the preset headphone equalizer effect
APP->SPAT: Adjust the headphone equalization effect yourself
end
end

group Turn off spatial audio
APP->SPAT: Pause spatial audio
APP->SPAT: Turn off spatial audio
APP->SPAT: Destroy the spatial audio engine
end

@enduml
