@startuml 
!include agora_skin.iuml

box "App"
participant "<size:40><&tablet>" as APP
end box

box "Your Server"
participant "<size:40><&hard-drive>" as SVR
end box

box "Video SDK"
participant "<size:40><&layers>" as SDK
end box

box "Agora SDRTN®"
participant "<size:40><&cloud>" as RTN
end box

group Token authentication
APP->SVR: Request a token\nwith a uid and channel name
APP<--SVR: Generate and return a token
APP->SDK: Join the corresponding channel with uid, channel name,\n and token
SDK<-->RTN: Verify the token
SDK-->APP: Successfully joined the channel
end

@enduml
