@startuml
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "RTC SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

USR -> APP: Open app
APP -> APP: Initialize the Agora RTC SDK engine: \n agoraEngine = createAgoraRtcEngine()
APP -> API: Enable the video module: \n agoraEngine.enableVideo()
APP -> APP: Register the event handler: \n agoraEngine.registerEventHandler
APP -> APP: Setup AgoraVideoView widgets \n for local and remote videos

group Video Call
USR -> APP: Join a call
APP -> API: Set a client role: \n agoraEngine.setClientRole
APP -> API: Set a channel profile: \n agoraEngine.setChannelProfile
APP -> APP: Retrieve authentication token
APP -> API: Join a channel using the token:\n agoraEngine.joinChannel
APP -> APP: Start local peview: \n agoraEngine.startPreview()
APP <- API: Remote user joined: \n RtcEngineEventHandler onUserJoined:
APP <-> API: Send and receive data streams
APP -> APP: Display remote video using AgoraVideoView
end

USR -> APP: Leave call
APP -> API: Leave the channel\n agoraEngine.leaveChannel()
USR -> APP: Close app

@enduml