@startuml
!include agora_skin.iuml

box "Call implementer"
participant "Client" as AC

participant "Client" as AC2
end box


box "Agora"
participant "Agora Platform" as AP
end box



group Run call
AC -> AC: Connect to local audio and video resources
AC -> AP: Join channel
AC -> AP: Send audio and video to channel

AC2 -> AC2: Connect to local audio and video resources
AC2 -> AP: Join channel
AP -> AC2: Send audio and video to channel

AC <-> AC2: Communicate
end

group End call

AC2 -> AC2: Close audio and video
AC2 -> AP: Leave channel

AC -> AC: Close audio and video
AC -> AP: Leave channel

end


@enduml