@startuml

!include ../video-sdk/agora_skin.iuml


box "Implemented by you"

participant  "Token server" as TS

participant "Your app" as APP

end box


box "Agora"
participant "Signaling" as API
end box

group Log in to Signaling using authentication
APP -> TS: Request an RTM token using:\n App Id, user Id
TS -> TS: Validate request against internal security\n and generate token
TS -> APP: Return RTM token to App
APP -> APP: Initiate the Signaling Engine using\n App Id, user Id and the RTM token
APP -> API: Log in to Signaling
API -> API: Validate the token
API -> APP: Log in user, then trigger callback
end

group Join a stream channel
APP -> TS: Request an RTC token using:\n App Id, user Id, and stream channel name
TS -> TS: Validate request against internal security\n and generate token
TS -> APP: Return RTC token to App
APP -> API: Join a stream channel using\n channel name, user Id, and the RTC token
end

group Renew token
API -> APP: Trigger event: token privilege will expire
APP -> TS: Request a token using:\n App Id, user ID
TS -> TS: Validate against internal security\n and generate token
TS -> APP: Return token to App
API -> APP: Send token to Signaling with a \ncall to renew token
API -> API: Validate the token
API -> APP: Trigger callback
end

@enduml

