@startuml

!include ../video-sdk/agora_skin.iuml


box "Implemented by you"

participant  "Token server" as TS

participant "Your app" as APP

end box


box "Agora"
participant "Signaling" as API
end box

group Log in to Signaling using authentication
TS -> TS: Configure your token server using\n your App Id and App Certificate
APP -> TS: Request an RTM token using a user Id
TS -> TS: Validate request against internal security\n and generate a token
TS -> APP: Return RTM token to App
APP -> APP: Initiate the Signaling Engine using\n the App Id
APP -> API: Log in to Signaling using\n the user Id and the RTM token
API -> API: Validate the token
API -> APP: Log in user, then trigger callback
end

group Join a stream channel
APP -> TS: Request an RTC token using\n a user Id, and a stream channel name
TS -> TS: Validate request against internal security\n and generate token
TS -> APP: Return RTC token to App
APP -> API: Join a stream channel using\n channel name, user Id, and the RTC token
end

group Renew token
API -> APP: Trigger event:\n token privilege will expire
APP -> TS: Request an RTM token using\n the user ID
TS -> TS: Validate request against internal security\n and generate a token
TS -> APP: Return RTM token to App
API <- APP: Send RTM token to Signaling with a \ncall to renew token
API -> API: Validate the token
API -> APP: Trigger callback
end

@enduml