@startuml

!include ../video-sdk/agora_skin.iuml



box "Implemented by you"

participant  "Token server" as TS

participant "Your app" as APP

end box


box "Agora"
participant "Signaling" as API
end box

APP -> APP: Initiate the Signaling Engine

group Join channel using authentication
APP -> TS: Request a token using:\n App Id, user ID
TS -> TS: Validate against internal security\n and generate token
TS -> APP: Return token to App

APP -> API: Log in to Signaling using\n UID and token.
API -> API: Validate the token
API -> APP: Log in user, then trigger callback
end

group Renew token
API -> APP: Trigger event: token privilege will expire
APP -> TS: Request a token using:\n App Id, user ID
TS -> TS: Validate against internal security\n and generate token
TS -> APP: Return token to App
API <- APP: Send token to Signaling with a \ncall to renew token
API -> API: Validate the token
API -> APP: Trigger callback
end

@enduml

