@startuml 
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Implemented by you"
actor "Admin" as ADMIN
participant "App" as APP
participant "Enterprise Firewall" as FIREWALL
end box

box "Provided by Agora"
participant "Cloud Proxy" as PROXY
participant "SDRTN®" as API
end box

ADMIN -> FIREWALL: Whitelist IP addresses and ports\n for Cloud Proxy in the firewall.

USR -> APP: Open the app
APP -> APP: Initialize the Signaling Engine

group Enable cloud proxy
APP -> APP: Call the method to enable\na Cloud Proxy connection
APP -> FIREWALL: Request access to \n Cloud Proxy
FIREWALL-> FIREWALL : Check whitelist to grant\n access
FIREWALL -> PROXY: Request access to \n Cloud Proxy
PROXY -> APP: Proxy information 
end

USR -> APP: Join a channel

APP -> PROXY: Join a channel
PROXY -> API: Ask to join a channel
API -> PROXY: Join success
PROXY -> APP: Join success
APP -> PROXY: Send data stream
PROXY <-> API: Send and receive data stream
PROXY -> APP: Receive data stream

USR -> APP: Leave a channel
APP -> PROXY: Leave the channel
PROXY -> API: Channel leave


@enduml