@startuml

!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Signaling SDK" as APP
end box

box "Agora"
participant "Signaling" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Create a signalingEngine instance
APP -> APP: Add event listeners
APP -> APP: Set the authentication token
APP -> API: Log in to Signaling
end

group Messages
USR -> APP: Subscribe to a channel
APP -> API: signalingEngine.subscribe
USR -> APP: Publish message
APP -> API: signalingEngine.publish
APP -> APP: Listen for message events
API -> APP: message
APP -> USR: Receive message
end

group Close
USR -> APP: Log out
APP -> API: Log out of Signaling
end

@enduml