@startuml

!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "<size:40><&layers>\n Signaling SDK" as APP
end box

box "Agora"
participant "<size:40><&cloud>\n Signaling" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Create a RtmClient instance: \n mRtmClient = RtmClient.create
APP -> APP: Add event listeners
end

group Login
USR -> APP: Log in to Signaling: 
APP -> APP: Set the authentication token
APP -> API: mRtmClient.login
end

group Messages
USR -> APP: Publish message
APP -> API: mRtmClient.publish
USR -> APP: Subscribe to a channel
APP -> API: mRtmClient.subscribe
APP -> APP: Listen for message events
API -> APP: message: onMessageEvent
APP -> USR: Receive message
end

group Close
USR -> APP: Log out
APP -> API: mRtmClient.logout
APP -> APP: Clean up: \n mRtmClient.release
end

@enduml