@startuml

!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "<size:40><&layers>\n Signaling SDK" as APP
end box

box "Agora"
participant "<size:40><&cloud>\n Signaling" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Create a RtmClient instance: \n final (status, client) = await RTM(appId, userId);
APP -> APP: Add event listeners
end

group Login
USR -> APP: Log in to Signaling: 
APP -> APP: Get the authentication token
APP -> API: rtmClient.login(token)
end

group Messages
USR -> APP: Publish message
APP -> API: rtmClient.publish
USR -> APP: Subscribe to a channel
APP -> API: rtmClient.subscribe
APP -> APP: Listen for message events
API -> APP: message: onMessageEvent
APP -> USR: Receive message
end

group Close
USR -> APP: Log out
APP -> API: rtmClient.logout
APP -> APP: Clean up: \n rtmClient.release
end

@enduml