@startuml

!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "<size:40><&layers>\n Signaling SDK" as APP
end box

box "Agora"
participant "<size:40><&cloud>\n Signaling" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Create a RtmClient instance: \n initWithConfig
APP -> APP: Add event listener: didReceiveMessageEvent
end

group Login
USR -> APP: Log in to Signaling: 
APP -> APP: Set the authentication token
APP -> API: loginByToken
end

group Messages
USR -> APP: Publish message
APP -> API: publish
USR -> APP: Subscribe to a channel
APP -> API: subscribeWithChannel
APP -> APP: Listen for message events
API -> APP: message: didReceiveMessageEvent
APP -> USR: Receive message
end

group Close
USR -> APP: Log out
APP -> API: logout
APP -> APP: Clean up: destroy
end

@enduml