@startuml 
!include agora_skin.iuml

participant "Idle" as idle
participant "Connecting" as connecting
participant "Connected" as connected
participant "Disconnected" as disconnected
participant "Suspended" as suspended
participant "Failed" as failed

group Successful login after initialization
idle -> connecting: login
connecting -> connected: Success
end

group An established connection is dropped and restored after the first attempt
connected -> disconnected: Connection dropped
disconnected -> connecting: Auto-reconnecting
connecting -> connected: Success
end

group An established connection is dropped and restored on the second attempt:
connected -> disconnected: Connection dropped
disconnected -> connecting: Auto-reconnecting
connecting -> disconnected: Failure
disconnected -> connecting: Auto-reconnecting
connecting -> connected: Success
end

group Reconnection attempts fail after 2 minutes
idle -> connecting: Login
connecting -> disconnected: Failure
disconnected -> connecting: Auto-reconnecting
connecting -> disconnected: Failure
disconnected -> suspended: After 2 minutes
end

group Successful reconnection after being in the suspended state
suspended -> connecting: Auto-reconnecting
connecting -> suspended: Failure
suspended -> connecting: Auto-reconnecting
connecting -> connected: Success
end

group Login fails due to a fatal error, followed by a successful re-login
idle -> connecting: Login
connecting -> failed: Fatal error
failed -> connecting: Re-login after removing the cause of the error
connecting -> connected: Success
end

group A logout operation while connected
connected -> idle: Logout
end

@enduml
