@startuml

!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Signaling SDK" as APP
end box

box "Agora"
participant "Signaling" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Create a signalingEngine instance
APP -> APP: Add the presence event listener
APP -> APP: Set the authentication token
APP -> API: Log in to Signaling
end

group Presence notifications
USR -> APP: Join a channel
APP -> API: Subscribe to a channel \nand enable presence events for the channel
API -> APP: Presence event:\n A remote user joins, leaves \nor changes status in the channel
APP -> APP: Read the event arguments
APP -> USR: Inform users 
end

group Presence queries
USR -> APP: Load the list of users in the channel
APP <-> API: Call getOnlineUsers
USR -> APP: Load the channel list for a user
APP <-> API: Call getUserChannels
end

group User status
USR -> APP: Set own status
APP -> API: Call setState
USR -> APP: Query the status of a remote user
APP <-> API: Call getState
end

group Close
USR -> APP: Log out
APP -> API: Log out of Signaling
end

@enduml