@startuml

!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Signaling SDK" as APP
end box

box "Agora"
participant "Signaling" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Create a Signaling client
APP -> APP: Add client event callbacks
APP -> APP: Create a Signaling channel
APP -> APP: Add channel event callbacks
APP -> API: Log in to Signaling
APP -> API: Join a channel
end

group Read and write user metadata
APP -> API: Set local user metadata
USR -> APP: Change user information
APP -> API: Add, update, or delete local user metadata
APP -> API: Subscribe to metadata of remote users
APP <- API: On user metadata updated callback
APP <- API: Retrieve metadata of a remote user
end

group Read and write channel metadata
APP -> API: Set channel metadata
USR -> APP: Update channel information
APP -> API: Add, update, or delete channel metadata
APP <- API: On channel metadata updated callback
APP <- API: Retrieve channel metadata
end

group Use locks
APP -> API: Set a lock
USR -> APP: Update channel metadata with locking
APP -> API: Acquire the lock
APP -> API: Specify the lock name when updating metadata
end

group Close
USR -> APP: Leave the channel
APP -> API: Release locks
APP -> API: Unsubscribe from user metadata update notifications
APP -> API: Log out of Signaling
end

@enduml