@startuml 
!include agora_skin.iuml

participant "Idle" as idle
participant "Connecting" as connecting
participant "Connected" as connected
participant "Failed" as failed

group Successfully joined a channel after initialization
idle -> connecting: Join
connecting -> connected: Success
end

group An established connection is dropped and restored after the first attempt
connected -> connecting: Connection dropped
connecting -> connected: Success
end

group An established connection is dropped and restored on the second attempt:
connected -> connecting: Connection dropped
connecting -> connecting: Auto-reconnecting
connecting -> connected: Success
end

group Reconnection attempts fail after 20 minutes
idle -> connecting: Join
connecting -> connecting: Auto-reconnecting
connecting -> connecting: Auto-reconnecting
connecting -> failed: After 20 minutes
end

group Join fails due to a fatal error, followed by a successful re-login
idle -> connecting: Join
connecting -> connecting: Auto-reconnecting
connecting -> failed: Fatal error
failed -> connecting: Re-join after removing the cause of the error
connecting -> connected: Success
end

group A logout operation while connected
connected -> idle: Leave
end

@enduml
