@startuml

!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Signaling SDK" as APP
end box

box "Agora"
participant "Signaling" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Create a signalingEngine instance
APP -> APP: Add user event callbacks
APP -> APP: Set the authentication token
APP -> API: Log in to Signaling
end

group Channel

USR -> APP: Create stream channel
APP <-> API: Create channel or add user to channel
USR -> APP: Subscribe to a channel
API <-> APP: Channel events

group Topic
USR -> APP: Join topic
APP <-> API: Create topic or add user to topic
USR -> APP: Subscribe to topic
API <-> APP: Topic events
group Messages

USR -> APP: Send message
APP -> API: Publish message to topic

API -> APP: Message from topic
APP -> APP: Listen for message events
APP -> USR: Receive message
end
USR -> APP: Leave topic
APP <-> API: Leave topic

end
USR -> APP: Leave channel
APP <-> API: Leave channel
end

group Presence

USR -> APP: Change status
APP -> APP: listen for user events
API -> APP: ConnectionStateChanged
APP -> USR: Inform users

end
group Close
USR -> APP: Log out
APP -> API: Log out of Signaling
end

@enduml