@startuml 
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Implemented by you"
participant "Web server" as SVR
participant "App" as APP
end box

box "Provided by Agora"
participant "SDRTN®" as API
end box
USR -> APP: Login
APP <-> API: Login authentication
note over API: No notification
USR -> APP: Create channel
APP -> API: Create channel
API -> APP: Open channel
API -> SVR: Notification 101: \n `channel name` opened at `time`.
SVR -> SVR: Authenticate notification \nsignature
SVR -> API: 200 OK

note over APP: Notifications sent and acknowledged for all channel events

API -> APP: Close channel
API -> SVR: Notification 102: \n `channel name` destroyed at `time`.
SVR -> SVR: Authenticate notification \nsignature
SVR -> API: 200 OK
USR -> APP: Logout
APP -> API: Logout
note over API: No notification
@enduml
