blank_issues_enabled: false
contact_links:
  - name: SDK bugs and feature requests.
    url: https://agora-ticket.agora.io/
    about: Do you have a bug or feature request related to one of Agora's SDKs?