name: "[Internal] Milestone management"
description: Checklist for milestone tasks
title: "[Internal] Milestone management"
labels: 'Enhancement'
assignees: atovpeko

body:
  - type: markdown
    attributes:
      value: "❗️ This Issue template is for Agora use only ❗️"

  - type: textarea
    attributes:
      label: Details
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: "Take the following project management steps to fulfill this milestone:"
      options:
        - label: "Run the full scope of the proposed EN doc updates by the PO"
          required: false
        - label: "Merge all PRs and close relevant tickets when the work is done"
          required: false
        - label: "Create and share a Vercel instance for review and stakeholder signoff"
          required: false
        - label: "Implement comments from stakeholders until fully resolved"
          required: false
        - label: "Publish updates to https://docs.agora.io/en/"
          required: false
        - label: "Inform the stakeholders"
          required: false
        - label: "Close the milestone"
          required: false
