name: Docs update request
description: Request an update or correction to documentation
title: "[Bug]: "
labels: 'Bug'
assignees: saudsami, atovpeko

body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Select the platform for the documentation update.
      options:
        - All or multiple (please specify)
        - Android
        - iOS
        - Web
        - macOS
        - Windows
        - Electron
        - Unity
        - Flutter
        - React Native
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Platform details
    validations:
      required: false

  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Select the product for the documentation update.
      options:
        - All or multiple (please specify)
        - Conversational AI
        - Realtime Communication
        - Chat
        - Signaling
        - Interactive Whiteboard
        - IoT SDK
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Product details
    validations:
      required: false

  - type: textarea
    id: business_case
    attributes:
      label: Business Case
      description: Explain how addressing this documentation issue will benefit Agora customers or yourself.
    validations:
      required: true

  - type: textarea
    id: subject_matter_expert
    attributes:
      label: Subject Matter Expert
      placeholder: |
        Technical: @saudsami
        Language: @atovpeko
    validations:
      required: false

  - type: textarea
    id: documentation_link
    attributes:
      label: Documentation Link
      description: Provide links to the relevant documentation that needs an update or correction.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Indicate the products and documents that should be updated. If unsure, leave it to @atovpeko to decide.
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - The documentation update must be technically accurate.
        - It should be easy for users to follow and understand.
        - It should adhere to the template structure.
        - It should follow the Google Developer Style Guide.
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Include any additional details, such as screenshots or context, that will help in addressing this documentation issue.
    validations:
      required: false
