name: "[Internal] Rewrite a document according to the new architecture"
description: Describe this issue template's purpose here.
title: "Rewrite the '<Doc Title>' doc in POC3 style"
labels: 'Enhancement'
assignees: saudsami

body:
  - type: markdown
    attributes:
      value: "❗️ This Issue template is for Agora use only ❗️"

  - type: textarea
    id: business_case
    attributes:
      label: Business case
      value: |
        The POC3 reference app simplifies the integration process of Video SDK. Clients can simply clone the code repository to experience and test product features. Add code for the implementation of **Document title** to the `video-sdk-samples-<platform>` code repository. Update the document to POC3 style and include the updated code. Use conditional blocks, where required, to create variants for Interactive live streaming, Broadcast Streaming, and Voice calling
    validations:
      required: true

  - type: textarea
    id: subject_matter_expert
    attributes:
      label: Subject Matter Expert
      value: |
        - Technical: Saud
        - Language: Anastasia
        - PM: Max (only if essential)
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      placeholder: |
        The products and documents to be updated:
        * The code repository for your platform.
        * The README file in the sample code folder.
        * The Video calling document for the feature: <document-link>
    validations:
      required: true

  - type: textarea
    id: platforms
    attributes:
      label: Platforms
      placeholder: |
        - [Android](https://github.com/AgoraIO/video-sdk-samples-android) - Saud
        - [iOS](https://github.com/AgoraIO/video-sdk-samples-ios) - Dasun
        - [Web](https://github.com/AgoraIO/video-sdk-samples-js) - Kishan
        > ... (and similarly for all other platforms)
    validations:
        required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      placeholder: |
        * The code uses best practices, runs without errors, and demonstrates the product feature.
        * The documentation is technically correct, easy to use, follows the template structure, and follows the Google Developer Style Guide.
    validations:
      required: true

  - type: textarea
    id: additional_valuable_information
    attributes:
      label: Additional valuable information
      placeholder: |
        * Branch from and merge to the milestone branch.
        * Use the same branch name in the code and docs repositories
    validations:
      required: false
