@startuml
!include agora_skin.iuml

participant "App Client" as APP
participant "App Server" as SVR
participant "Agora Chat SDK" as SDK
participant "Agora Chat Server" as CHAT

APP -> SVR: 1. Request a token \nwith user privileges
APP <- SVR: 2. Generate a token and pass it to the client
APP -> SDK: 3. Log in to Agora Chat with the user name and token
SDK -> CHAT: 4. Validate the token 
SDK <- CHAT: 5. Log in successfully
APP <- SDK: 6. Trigger the callback after a successful login
@enduml
