@startuml

!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Chat SDK" as APP
end box

box "Agora"
participant "Agora \nChat" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Get a AgoraChat SDKClient instance \n SDKClient.Instance
APP -> APP: Initialize the instance: \n SDKClient.Instance.InitWithOptions(options)
APP -> APP: Add message event callbacks: \nSDKClient.Instance.ChatManager.AddChatManagerDelegate(...)
APP -> APP: Add connection event callbacks: \nSDKClient.Instance.AddConnectionDelegate(...)
end

group Log in
USR -> APP: Join a chat
APP -> APP: Retrieve authentication token for the user
APP -> API: Log in to Agora Chat:\n SDKClient.Instance.LoginWithAgoraToken(...)
API -> APP: onConnected() callback
end

group Send messages
USR -> APP: Send a message
APP -> APP: Create a ChatMessage
APP -> API: Send the ChatMessage: \nSDKClient.Instance.ChatManager.SendMessage(...)
end

group Receive messages
APP <- API: onMessageReceived(messages) callback
APP -> USR: Display message
end

group Close
USR -> APP: Leave the chat
APP -> API: Log out: \n  SDKClient.Instance.Logout(...)
end

@enduml

