@startuml
!include ../video-sdk/agora_skin.iuml

participant "Your App Server" as APP

participant "Agora Chat Server" as CHAT


APP -> APP: 1. Generate a token \nwith app privileges
APP -> CHAT: 2. Use the token to call \nAgora RESTful APIs
CHAT -> CHAT: 3. Validate the token 
CHAT -> APP: 4. Return the response after successful API call

@enduml
