@startuml

!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Chat SDK" as APP
end box

box "Agora"
participant "Chat \nServer" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Get a ChatClient instance \n agoraChatClient = ChatClient.getInstance()
APP -> APP: Initialize the instance: \n agoraChatClient.init(context, options)
APP -> APP: Add message event callbacks: \nagoraChatClient.chatManager().addMessageListener(...)
APP -> APP: Add connection event callbacks: \nagoraChatClient.addConnectionListener(...)
end

group Log in
USR -> APP: Join a chat
APP -> APP: Retrieve authentication token for the user
APP -> API: Log in to the chat server:\n agoraChatClient.loginWithAgoraToken(...)
API -> APP: onConnected() callback
end

group Send messages
USR -> APP: Send a message
APP -> APP: Create a ChatMessage
APP -> API: Send the ChatMessage: \nagoraChatClient.chatManager().sendMessage(message)
end

group Receive messages
APP <- API: onMessageReceived(messages) callback
APP -> USR: Display message
end

group Close
USR -> APP: Leave the chat
APP -> API: Log out: \n  agoraChatClient.logout(...)
end

@enduml

