@startuml

!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Chat SDK" as APP
end box

box "Agora"
participant "Chat \nServer" as API
end box

group Initialize
USR -> APP: Open app
APP -> APP: Init a chat SDK instance: \n SDKClient.Instance.InitWithOptions(options);
APP -> APP: Add message event callbacks: \n SDKClient.Instance.ChatManager.AddChatManagerDelegate(this);
end

group Log in
USR -> APP: Join a chat
APP -> APP: Retrieve authentication token for the user
APP -> API: Log in to the chat server:\n SDKClient.Instance.LoginWithAgoraToken(...)
API -> APP: onConnected() callback
end

group Send messages
USR -> APP: Send a message
APP -> APP: Create a ChatMessage
APP -> API: Send the ChatMessage: SDKClient.Instance.ChatManager.SendMessage(...)
end

group Receive messages
APP <- API: onMessageReceived(messages) callback
APP -> USR: Display message
end

group Close
USR -> APP: Leave the chat
APP -> API: Log out: \n  agoraChatClient.Logout(...)
end

@enduml

