@startuml
!include agora_skin.iuml

actor "User" as USR
participant "Your App Server" as APP
participant "Agora Tools\n(in your app server)" as TOOLS
participant "Agora Chat Server" as CHAT


APP -> TOOLS: 1. Generate a token \nwith app privileges and cache it
TOOLS -> APP: Return a token \nwith app privileges
USR -> APP: 2. Request a token with user priviliges
APP -> CHAT: Get the token with app priviliges\n from cache and create an Agora Chat user
APP <-- CHAT: Return the UUID of the Agora Chat user
APP -> TOOLS: Use the UUID to generate a token with user privileges
APP <-- TOOLS: Return a token with user privileges
USR <- APP: Return a token with user privileges

@enduml
