@startuml composite-recording-recording-logic
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Recording SDK" as APP
end box

box "Agora"
participant "SD-RTN" as API
end box

USR -> APP: Open App
APP -> APP: Create and initialize a recorder 

group Enable the composite recording mode
APP -> APP: initialize(agoraService, true): \n Set enableMix to true for composite recording
USR -> APP: Join a channel

group Join a channel
APP -> API: subscribeAllAudio(): \n Subscribe all audio streams
APP -> API: subscribeAllVideo(): \n Subscribe all video streams
APP -> API: joinChannel(): \n Join a channel
API -> APP: onUserJoined: \n media streams
end

USR -> APP: Start recording

group Set a watermark and recording layout
APP -> APP: setRecorderConfig(): \n Set recorder settings
APP -> APP: setVideoMixingLayout(): \n Set the video size and resolution
APP -> APP: enableAndUpdateVideoWatermarks: \n Update watermark
end

group Start recording
APP -> APP: startRecording(): \n Start composite recording
end

USR -> APP: Start recording

group Stop recording
APP -> APP: stopRecording(): \n Stop composite recording
end

USR -> APP: Close App
APP -> APP: Clean up resources

@enduml