@startuml individual-recording-logic-cpp
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Recording SDK" as APP
end box

box "Agora"
participant "SD-RTN" as API
end box

USR -> APP: Open App
APP -> APP: Create and initialize a recorder 

group Enable the individual recording mode
APP -> APP: initialize(agoraService, false): \n Set enableMix to false for individual recording
USR -> APP: Join a channel

group Join a channel
APP -> API: subscribeAllAudio(): \n Subscribe all audio streams
APP -> API: subscribeAllVideo(): \n Subscribe all video streams
APP -> API: joinChannel(): \n Join a channel
API -> APP: onUserJoined: \n media streams
end

USR -> APP: Start recording

group Set a watermark
APP -> APP: setRecorderConfigByUid(): \n Set recorder settings
APP -> APP: enableAndUpdateVideoWatermarksByUid: \n Update watermark
end

group Start recording
APP -> APP: startRecordingByUid(): \n Start individual recording
end

USR -> APP: Start recording

group Stop recording
APP -> APP: stopRecordingByUid(): \n Enable the individual recording mode
end

USR -> APP: Close App
APP -> APP: Clean up resources

@enduml