@startuml
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Recording SDK" as APP
end box

box "Agora"
participant "SDRTN<sup>®</sup>" as API
end box

USR -> APP: Open App

group Create Agora service
APP -> APP: AgoraService() :\nCreate an instance
APP -> APP: initialize():\nInitialize the instance
end

group Configure a media recorder instance
APP -> APP: createAgoraMediaComponentFactory():\nCreate a media factory component
APP -> APP: createMediaRtcRecorder():\nCreate a media recorder
APP -> APP: initialize():\nInitialize the instance
APP -> APP: registerRecorderEventHandle():\nRegister events
end

USR -> APP: Join a channel

group Join a channel and start recording
APP -> APP: setRecorderConfig():\nSet recorder configuration
APP -> API: joinChannel():\nJoin a channel
APP -> API: subscribeAllAudio():\nSubscribe all audio streams
APP -> API: subscribeAllVideo():\nSubscribe all video streams
APP -> API: startRecording():\nStart audio and video recording
API -> APP: media streams
end

USR -> APP: Close App

group Clean up resources
APP -> API: unsubscribeAllAudio():\nUnsubscribe all audio
APP -> API: unsubscribeAllVideo():\nUnsubscribe all video
APP -> APP: stopRecording():\nStop recording media streams
APP -> APP: unregisterRecorderEventHandle():\nUnregister events
APP -> API: leaveChannel():\nLeave the channel
APP -> APP: release():\nRelease the Agora service instance
end

@enduml