
scale max 1000 width
skinparam linetype ortho
hide stereotype

skinparam backgroundColor transparent
skinparam Shadowing false
skinparam BoundaryBackgroundColor transparent
skinparam BoundaryBorderColor #0a9efdff
skinparam DiagramBorderColor #0a9efdff
skinparam defaultTextAlignment center
skinparam SequenceMessageAlign center
skinparam ReferenceBorderThickness 2

skinparam sequence {

'Users and boundries (DBS for example)
    ActorBorderThickness 3
   	ActorBorderColor #0a9efdff
	ActorBackgroundColor transparent
	ActorFontColor #0a9efdff
	ActorFontName Roboto
    ActorFontStyle bold
    ActorFontSize 14

    AgentBackgroundColor #0a9efdff

'Arrows
   	ArrowFontColor #0a9efdff
   	ArrowFontSize 14
   	ArrowFontStyle bold
    ArrowColor #ee4c14
    ArrowThickness 2

    RectangleBorderThickness 3
    BoxBackgroundColor #f3f3f3
    BoxBorderColor #0a9efdff

'Capability
   	BoxFontColor #0a9efdff
   	BoxFontName Roboto
   	BoxFontStyle bold
   	BoxFontSize 16

    BoundaryBackgroundColor #0a9efdff
    BoundaryBorderColor #0a9efdff
    BoundaryFontColor #0a9efdff
    BoundryFontName Roboto
    BoundaryStereotypeFontColor #0a9efdff

    ClassBorderColor #0a9efdff
    ComponentBorderColor #0a9efdff

    DividerBackgroundColor white
    DividerBorderColor #0a9efdff
    DividerBorderThickness 3
    DividerFontColor #0a9efdff
    DividerFontName Roboto
    DividerFontSize bold
    DividerFontStyle 14

' Loops but not the title text
    GroupBorderColor #0a9efdff
    GroupBorderThickness 2
    GroupFontName Roboto
    GroupFontSize 14
    GroupFontColor #0a9efdff
'Title text for loops
    GroupHeaderFontColor #0a9efdff
    GroupHeaderFontName Roboto
    GroupHeaderFontSize 14
    GroupHeaderFontStyle bold

   	LifeLineBorderColor #0a9efdff
   	LifeLineBackgroundColor #0a9efdff
   	LifeLineFontColor  #0a9efdff

'Services
   	ParticipantBorderColor #0a9efdff
   	ParticipantBackgroundColor white
   	ParticipantFontSize 14
   	ParticipantFontStyle bold
   	ParticipantFontName Roboto
   	ParticipantFontColor #0a9efdff
    ParticipantBorderThickness 2

    ReferenceBorderThickness 2


'   SwimlaneBorderThickness 2

    TitleFontColor #0a9efdff
    TitleFontName Roboto
    TitleFontSize 18
    TitleBorderThickness 5

}
skinparam interface {
  BackgroundColor #FFFFFF
  BorderColor #0a9efdff
  BorderThickness 1
  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bolds

}


skinparam usecase {
  BackgroundColor #FFFFFF
  BorderColor #ee4c14
  BorderThickness 1
  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

}

skinparam note {

  BackgroundColor #FFFFFF

  BorderColor #0a9efdff
  BorderThickness 1

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

}

skinparam activity {

  BackgroundColor #FFFFFF
  DiamondBackgroundColor #FFFFFF
  DiamondBorderColor #0a9efdff
  BorderColor #0a9efdff
  BorderThickness 4
  DiamondBackgroundColor #FFFFFF
  DiamondBorderColor #0a9efdff
  DiamondFontColor #0a9efdff
  activityDiamondFontName Roboto
  activityDiamondFontSize 14
  DiamondFontStyle bold
  StartColor #0a9efdff
  StopColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

}

skinparam card {
  BackgroundColor transparent
  BorderColor transparent
  BorderThickness 0
  FontColor transparent
}


skinparam rectangle {

  BackgroundColor #FFFFFF

  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

  shadowing true
}

skinparam agent {

  BackgroundColor #FFFFFF
  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

  shadowing true
}

skinparam folder {

  BackgroundColor #FFFFFF

  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

  shadowing true
}

skinparam file {

  BackgroundColor #FFFFFF

  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

  shadowing true
}

skinparam cloud {

  BackgroundColor #FFFFFF

  BorderColor #0a9efdff
  BorderThickness 4

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

}

skinparam class {

  BackgroundColor #FFFFFF

  BorderColor #0a9efdff
  BorderThickness 1

  StartColor #0a9efdff
  BarColor #0a9efdff
  EndColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold



}

'For services
skinparam component {

  BackgroundColor  #FFFFFF

  BorderColor #0a9efdff
  BorderThickness 2

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold
}



'databases
skinparam database {

  BackgroundColor #f3f3f3

  BorderColor #0a9efdff
  BorderThickness 2

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

}


'For Capabilities
skinparam frame {

  ArrowColor #0a9efdff

  BackgroundColor #f3f3f3
  BorderColor #0a9efdff
  BorderThickness 4

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold
}


' External systems in architecture diagrams
skinparam node {

  ArrowColor #0a9efdff

  BorderThickness 2
  BackgroundColor #FFFFFF
  BorderColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

}

skinparam package {
  BorderThickness 2
  BackgroundColor #FFFFFF
  BorderColor #0a9efdff

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

}

' Activity diagrams, for different capabilities

skinparam partition {

  BackgroundColor #f3f3f3

  BorderColor #0a9efdff
  BorderThickness 2

  FontColor #0a9efdff
  FontName Roboto
  FontSize 14
  FontStyle bold

}

skinparam ArrowFontColor #0a9efdff
skinparam ArrowFontSize 14
skinparam ArrowFontStyle bold
skinparam ArrowColor #0a9efdff
skinparam ArrowThickness 2
skinparam ArrowFontName Roboto

skinparam linetype ortho
hide stereotype

!definelong AWSEntityColoring(e_stereo)

skinparam rectangle<<e_stereo>> {
    BackgroundColor AWS_BG_COLOR
    BorderColor orange
    Shadowing true
}
!enddefinelong

!definelong AWSEntity(e_alias, e_label, e_techn, e_color, e_sprite, e_stereo)
rectangle "<color:e_color><$e_sprite></color>\n\n==e_label" <<e_stereo>> as e_alias
!enddefinelong

!definelong AWSEntity(e_alias, e_label, e_techn, e_descr, e_color, e_sprite, e_stereo)
rectangle "<color:e_color><$e_sprite></color>\n\n==e_label" <<e_stereo>> as e_alias
!enddefinelong




