@startuml

!include agora_skin.iuml

' Create participants
box #E6F9FF
participant "<$app> App: Broadcaster" as app1
end box

box #F1F7FF
participant "<$sdk> Video SDK" as sdk 
end box

box #FFF7E7
participant "<$app-yellow> <color:#A66300>App: Audience" as app2
end box

' Sequence of actions
app1 -> app1: Custom Video Capture
app1 -> sdk: Push video to SDK,\n generate Alpha data
app1 -> sdk: Set local view,\n enable Alpha rendering
app2 -> sdk: Set remote view,\n enable Alpha rendering

@enduml
