@startuml

' Import sequence diagram skin
!include agora_skin.iuml

' Create participants
box #E6F9FF
participant "<$app> App: Broadcaster" as app1
end box
box #F1F7FF
participant "<$sdk> Video SDK" as sdk
end box
box #FFF7E7
participant "<$app-yellow> App: Audience" as app2
end box

' Title (optional)
app1 -> sdk: Start virtual background,\n separate the portrait and background
app1 -> sdk: Set video encoding properties,\n encode and send Alpha data
app1 -> sdk: Set up the local view,\n and enable Alpha rendering
app2 -> sdk: Set up the remote view,\n and enable Alpha rendering

@enduml
