@startuml

' Import sequence diagram skin
!include agora_skin.iuml

' Create participants
box #E6F9FF
participant "<$app> App: Broadcaster" as app1
end box
box #F1F7FF
participant "<$sdk> Video SDK" as sdk
end box
box #FFF7E7
participant "<$app-yellow> App: Audience" as app2
end box

' Title (optional)
app1 -> sdk: Start virtual background,\n separate person and background
app1 -> sdk: Set local view,\n enable Alpha rendering
app2 -> sdk: Set remote view,\n enable Alpha rendering

@enduml
