@startuml audio-and-voice-effects
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Video SDK" as APP
end box

box "Agora"
participant "SD-RTN" as API
end box

USR -> APP: Open App
APP -> APP: Create an Agora Engine instance using Video SDK
APP -> APP: Enable audio and video in Agora Engine

group Join
USR -> APP: Join a channel
APP -> APP: Retrieve authentication token to join a channel
APP -> API: Join the channel 
end

group Audio mixing
USR -> APP: Select an audio file
APP -> API: Proccess the audio file
USR -> APP: Start audio mixing
APP -> API: Play the audio file
USR -> APP: Stop mixing
APP -> API: Stop the audio file
end

group Change audio route
APP -> API: Set default audio route
APP -> API: Change the audio route temporarily
end

USR -> APP: Leave the channel
APP -> API: Leave the channel

@enduml
