@startuml
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Video SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

USR -> APP: Open App
APP -> APP: Create an Agora Engine instance using Video SDK
APP -> APP: Enable audio and video in Agora Engine

group Join
USR -> APP: Join a channel
APP -> APP: Retrieve authentication token to join a channel
APP -> API: Join the channel 
end

group Play audio effect
USR -> APP: Trigger sound effect
APP -> API: Play effect
APP -> API: Pause and resume effect
APP -> API: Set effect position
APP -> API: Set effect volume
APP <- API: On audio effect finished
end

group Audio mixing
USR -> APP: Control audio mixing
APP -> API: Start audio mixing
APP -> API: Stop audio mixing
end

group Voice effects
USR -> APP: Apply a voice effect
APP -> API: Set preset voice effect
APP -> API: Disable the voice effect
end

group Change audio route
APP -> API: Set default audio route
APP -> API: Change the audio route temporarily
end

USR -> APP: Leave the channel
APP -> API: Leave the channel

@enduml
