@startuml 
!include agora_skin.iuml

actor "User" as USR

box "Implemented by you"
actor "Admin" as ADMIN
participant "App" as APP
participant "Enterprise Firewall" as FIREWALL
end box

box "Provided by Agora"
participant "Cloud Proxy" as PROXY
participant "SDRTN®" as API
end box

ADMIN -> FIREWALL: Whitelist IP addresses and ports\n for Cloud Proxy in the firewall.

USR -> APP: Open the app
APP -> APP: Initialize the Agora Video\n SDK engine

USR -> APP: Join a channel

alt Join a channel directly
    APP -> API: Join a Channel
    API -> APP: Join Success
    APP <-> API: Send and receive data
else Join Channel failed
    APP -> API: Video SDK automatically attempts to connect securely on TLS 443
    API -> APP: Join Success
    APP <-> API: Send and receive data
else Connection attempt on TLS 443 failed: Enable cloud proxy
    APP -> APP: Call the method to enable\na Cloud Proxy connection
    APP -> FIREWALL: Request access to \n Cloud Proxy
    FIREWALL-> FIREWALL : Check whitelist to grant\n access
    FIREWALL -> PROXY: Request access to \n Cloud Proxy
    PROXY -> APP: Proxy information 
    APP -> PROXY: Join a channel
    PROXY -> API: Request to join a channel
    API -> PROXY: Join success
    PROXY -> APP: Join success
    APP -> PROXY: Send data stream
    PROXY <-> API: Send and receive data stream
    PROXY -> APP: Receive data stream
end

@enduml