@startuml
!include agora_skin.iuml

box "App: Host"
participant "<size:40><&tablet>" as APP
end box

box "SDK"
participant "<size:40><&layers>" as SDK
end box

box "Agora\n SDRTN®"
participant "<size:40><&cloud>" as RTN
end box

APP->SDK: Create and initialize the engine
APP->SDK: Join the channel and set\n the user role as the host
note right: Only the stream of \na host can be forwarded
SDK->RTN: Request to join the \nlive channel as a host

group Start
APP->SDK: Start cross-channel\n media stream forwarding
SDK->RTN: Request forwarding flow
SDK-->APP: The source channel host successfully\n joined the target channel
end

group Renew
APP->SDK: Update the target channel\n for media stream forwarding
SDK->RTN: Request an update to the\n forwarding channel
SDK-->APP: Target channels have been updated
end
group Pause
APP->SDK: Pause forwarding of media streams\n to all target channels
SDK->RTN: Request to pause forwarding flow
SDK-->APP: Pause forwarding media stream\n to target channel successful 
end
group Recover
APP->SDK: Resume forwarding media streams\n to all target channels,
SDK->RTN: Request to resume forwarding flow
SDK-->APP: Resume forwarding media streams\n to the target channel successful
end
group Stop
APP->SDK: Stop cross-channel\n media stream forwarding
SDK->RTN: Request to stop forwarding flow
SDK-->APP: Stopped media stream forwarding
end

APP->SDK: Leave channel
SDK->RTN: Request to leave channel
APP->SDK: Destroy the engine

@enduml
