
@startuml

!include agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open App
APP -> APP: Initiate the Video SDK engine:\n agoraEngine = AgoraRTC.createClient
APP -> APP: Start video in the engine:\n App.init
APP -> APP: Start local media:\n stream = AgoraRTC.createStream\n stream.init \n stream.play
group Host
USR -> APP: Start live streaming event
APP->APP: Retrieve authentication token to join channel
APP -> API: Set the user role as host:  \n agoraEngine.setClientRole("host")
APP -> API: Join a channel as host:\n agoraEngine.join

APP -> API: Push local media to the channel:\n agoraEngine.publish
end

group Audience
USR -> APP: Join live streaming event
APP->APP: Retrieve authentication token to join channel
APP -> API: Set the user role as audience: \n agoraEngine.setClientRole("audience")
APP -> API: Join the live streaming event:\n agoraEngine.join
API -> APP: Retrieve streaming from the other user: \n agoraEngine.on("stream-added")\n agoraEngine.subscribe\n  agoraEngine.on("stream-subscribed")
API -> APP: Receive data stream
end

USR -> APP: Leave live streaming event
APP -> API: agoraEngine.leave

@enduml
