
@startuml

!include agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open app
APP -> APP: Initiate the Video SDK engine.
APP -> APP: Start video in the engine.

group Host
USR -> APP: Start ILS event
APP -> APP: In an ILS event, only the hosts broadcast to the channel.
APP -> APP: Start local video.
APP -> API: Join the channel.
APP -> API: Send data stream.
end

group Audience
USR -> APP: Join ILS event
APP -> APP: In an ILS event, the audience views the broadcast made by channel hosts.
APP -> API: Join the channel.
APP -> API: Retrieve streaming from the other user.
API <-> APP: Receive data streams

end

USR -> APP: Leave ILS event
APP -> API: Stop local video.
APP -> API: Leave the channel.

USR -> APP: Close app
APP -> APP: Clean up local resources.

@enduml



!include agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open App
APP -> APP: AgoraRTC.createClient
APP -> APP: App.init
APP -> API: Client.join
API -> APP : join accepted



group Host
USR -> APP: Start broadcast
APP -> APP: stream = AgoraRTC.createStream
APP -> APP: stream.init
APP -> APP: stream.play
APP -> API: Client.publish
APP -> API: Send data stream
end

group Audience

USR -> APP: Join broadcast
API -> APP: Client.on("stream-added")
APP -> API: Client.subscribe
API -> APP: Client.on("stream-subscribed")
API -> APP: Receive data stream
APP -> APP: stream.play

end

USR -> APP: Leave broadcast
APP -> API: Client.leave


@enduml
