@startuml 
!include agora_skin.iuml

box "App"
participant "<size:40><&tablet>" as APP
end box

box "Video SDK"
participant "<size:40><&layers>" as SDK
end box

box "Agora SDRTN®"
participant "<size:40><&cloud>" as RTN
end box

group Create a local client
APP->SDK: AgoraRTC.createClient\n Set mode to 'live'
end

group Set user role
APP->SDK: Set the role to 'host' or 'audience'\n AgoraRTCClient.setClientRole
end

group Join channel
APP->SDK: AgoraRTCClient.join
SDK->RTN: Join channel request
end

group If the user role is 'host'
group Create and publish local audio and video tracks
APP->SDK: Create local audio track\n AgoraRTC.createMicrophoneAudioTrack
APP->SDK: Create local video track\n AgoraRTC.createCameraVideoTrack
APP->SDK: Publish local audio and video tracks\n AgoraRTCClient.publish
SDK->RTN: Send audio and video data
end
end

group Subscribe to remote users
APP<--RTN: Remote users publish audio and video tracks\n client.on("user-published")
APP->SDK: Get remote user object\n AgoraRTCClient.remoteUsers
APP->SDK: Subscribe to remote user object\n AgoraRTCClient.subscribe
SDK<-RTN: Receive audio and video data
APP->SDK: Get remote audio object\n AgoraRTCRemoteUser.audioTrack
APP->SDK: Get remote video object\n AgoraRTCRemoteUser.videoTrack
end

group Leave the channel
APP->SDK: Turn off the local audio track\n MicrophoneAudioTrack.close
APP->SDK: Turn off the local video track\n CameraVideoTrack.close
APP->SDK: Leave the channel\n AgoraRTCClient.leave
SDK->RTN: Request to leave the channel
end

@enduml
