
@startuml
!include agora_skin.iuml


actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open App
APP -> APP: Initiate the Agora Video SDK engine: \n agoraEngine = RtcEngine.create
APP -> APP: Enable the video module: \n agoraEngine.enableVideo()
APP -> APP: Set the channel profile: \n agoraEngine.setChannelProfile(CHANNEL_PROFILE_LIVE_BROADCASTING)

group Host
USR -> APP: Start a live streaming event
APP->APP: Retrieve authentication token to join channel
APP -> API: Set the role as host:\n  agoraEngine.setClientRole(Constants.CLIENT_ROLE_BROADCASTER)
APP -> APP: Setup local video:\n agoraEngine.setupLocalVideo(VideoCanvas)
APP -> APP: Start local preview:\n agoraEngine.startPreview()
APP -> API: Join a channel as host: \n agoraEngine.joinChannel
APP -> API: Send data stream
end

group Audience
USR -> APP: Join a live streaming event
APP -> APP: Retrieve authentication token to join channel
APP -> API: Set the user role as audience: \n agoraEngine.setClientRole(CLIENT_ROLE_AUDIENCE)
APP -> API: Join the channel: \n agoraEngine.joinChannel
APP -> API: Retrieve streaming from the hosts: \n agoraEngine.setupRemoteVideo
API -> APP: Receive data stream
end

USR -> APP: Leave the live streaming event
APP -> API: Leave the channel: \n agoraEngine.leaveChannel()

USR -> APP: Close app
APP -> APP: Clean up local resources\n  agoraEngine.destroy()


@enduml

