@startuml ils-call-logic-unity
!include agora_skin.iuml

actor "User" as USR

box "Your game"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open game
APP -> APP: Create an RtcEngine instance: \n RtcEngine = Agora.Rtc.RtcEngine.CreateAgoraRtcEngine()
APP -> API: Set channel profile: \n RtcEngine.SetChannelProfile(\n   CHANNEL_PROFILE_TYPE.CHANNEL_PROFILE_LIVE_BROADCASTING)
APP -> API: Set the context: \n RtcEngineContext context = new RtcEngineContext(_appID, 0, true, \n CHANNEL_PROFILE_TYPE.CHANNEL_PROFILE_LIVE_BROADCASTING, \n AUDIO_SCENARIO_TYPE.AUDIO_SCENARIO_DEFAULT)
APP -> APP: Initialize RtcEngine: \n RtcEngine.Initialize(context)

group Host
USR -> APP: Start a live streaming event
APP -> APP: Enable the video module: \n RtcEngine.EnableVideo()
APP -> API: Set the user role as host: \n RtcEngine.SetClientRole(\n  CLIENT_ROLE_TYPE.CLIENT_ROLE_BROADCASTER)
APP -> API: Join a channel as host: \n RtcEngine.JoinChannel()
end

group Audience
USR -> APP: Join a live streaming event
APP -> APP: Enable the video module: \n RtcEngine.EnableVideo()
APP -> API: Set the user role as audience: \n RtcEngine.SetClientRole(\n  CLIENT_ROLE_TYPE.CLIENT_ROLE_AUDIENCE)
APP -> API: Join the channel as audience: \n RtcEngine.JoinChannel()
end

USR -> APP: Leave call
APP -> API: Leave the channel: \n RtcEngine.LeaveChannel()
APP -> APP: Disable the video modules: \n RtcEngine.DisableVideo()
APP -> APP: Stop rendering the remote video: \n RemoteView.SetEnable(false)
APP -> APP: Stop rendering the local video: \n LocalView.SetEnable(false)

USR -> APP: Close game
APP -> APP: Clean up local resources: \n  RtcEngine.Dispose()

@enduml

