@startuml
!include agora_skin.iuml

box "App: Host"
participant "<size:40><&tablet>" as HOST
end box

box "Agora SDK"
participant "<size:40><&layers>" as SDK
end box

box "Agora"
participant "SD-RTN™" as API
end box

box "App: Audience"
participant "<size:40><&tablet>" as AUD
end box

group Hosts publish video streams
HOST -> SDK: Join channel
SDK -> API: Publish video streams in the channel
end

group Enable Cloud Transcoding
HOST -> API: Start cloud composite via RESTful API\nand forward to another channel
end

group Receiving end: customize composite layout
AUD -> SDK: Join the channel containing\nthe composite stream
SDK --> AUD: Send composite stream callback\nwith layout information
AUD -> SDK: Customize the local composite layout
end

@enduml