@startuml
!include agora_skin.iuml

box "App: Host"
participant "<size:40><&tablet>" as HOST
end box

box "Agora SDK"
participant "<size:40><&layers>" as SDK
end box

box "Agora"
participant "SD-RTN" as API
end box

box "App: Audience"
participant "<size:40><&tablet>" as AUD
end box

group The host publishes the video stream
HOST -> SDK: Join channel
SDK -> API: Publish video streams in the channel
end

group Enable cloud transcoding
HOST -> API: Open the cloud-based image through \nthe RESTful API and forward it to other channels
end

group Customize the combined image\n layout on the receiving end
AUD -> API: Join the channel where\n the combined image stream is located
API --> AUD: Send the combined image\n stream callback with layout information
AUD -> API: Customize the local layout\n of the combined image
end

@enduml
