@startuml
!include agora_skin.iuml

box "User"
participant "<size:40><&person>" as USR
end box


box "App"
participant "<size:40><&tablet>" as APP
end box

box "SDK"
participant "<size:40><&layers>" as SDK
end box

USR->APP: Request a device test
APP->SDK: Start echo test

group Audio test
USR->APP: Speak into the recording device
APP->USR: Hear your own voice\n through the playback device
note right: After 2 seconds\n(default delay)
end

group Video test
USR->APP: Enable the camera
APP->USR: See the camera feed in the app
note right: After a short ttime
end

USR->APP: Request to stop testing
APP->SDK: Stop echo test

@enduml
