@startuml
!include agora_skin.iuml
skinparam minClassWidth 100
skinparam Padding 10

start
:Your subscribed package;
:Usage deducted from \nyour subscribed package;
if (Is your usage within \nyour package limit?) then (Yes)
  :Billing ends;
  stop
else (No)
  if (Have you purchased \na top-up package?) then (Yes)
    if (Does your usage exceed \nthe top-up package limit?) then (Yes)
      :You pay through\noverage post-payment;
      :Billing ends;
      stop
    else (No)
      :Billing ends;
      stop
    endif
  else (No)
    :You pay through\noverage post-payment;
    :Billing ends;
    stop
  endif
endif
@enduml