@startuml
!include agora_skin.iuml

box "User"
participant "<size:40><&person>" as USR
end box

box "App"
participant "<size:40><&tablet>" as APP
end box

box "Agora SD-RTN"
participant "<size:40><&cloud>" as RTN
end box

USR -> APP: Start the app

group Restrict media zones
APP -> APP: Set areaCode in the Agora engine\n configuration to include/exclude media zones
APP -> APP: Initialize the Agora engine
APP -> RTN: Connect to SD-RTN in the\n specified media zone(s)
RTN -> APP: Success response
end

USR -> APP: Select a channel to join
APP -> RTN: Join a channel with user \nId, channel name, and token
RTN -> APP: Join accepted

@enduml
