@startuml
!include agora_skin.iuml

box "Extension process"
participant "<size:40><&plus>" as EXT
end box

box "Main process"
participant "<size:40><&layers>" as MAIN
end box

box "Agora SD-RTN"
participant "<size:40><&cloud>" as RTN
end box

group Screen sharing
MAIN->EXT: Send screen sharing command
EXT->MAIN: Publish a screen sharing stream
RTN->MAIN: Subscribe to other streams
MAIN->RTN: Publish screen sharing stream

end

@enduml
