@startuml
!include agora_skin.iuml

box "Extension process"
participant "<size:40><&layers>" as EXT
end box

box "Main process"
participant "<size:40><&layers>" as MAIN
end box

box "Agora SD-RTN"
participant "<size:40><&cloud>" as RTN
end box

group Screen sharing
MAIN->EXT: One screen sharing command send
EXT->MAIN: One screen sharing stream release
RTN->MAIN: One subscription to other streams
MAIN->RTN: One screen sharing stream release

end

@enduml
