@startuml
!include agora_skin.iuml

box "App"
participant "<size:40><&tablet>" as APP
end box

box "Agora\nEngine"
participant "<size:40><&layers>" as SDK
end box

box "Spatial audio\nEngine"
participant "<size:40><&map>" as SPAT
end box

APP->SDK: Create and initialize Agora engine
APP->SPAT: Initialize the spatial audio engine
APP->SDK: Set up an audio profile and audio scenario
APP->SDK: Set up a channel profile and client role
APP->SDK: Join a channel

APP->SDK: Mute all remote audio streams
APP->SPAT: Set the number of receivable audio streams
APP->SPAT: Set the audio receiving range
APP->SPAT: Set the distance unit in meters

group Spatial audio effect for users
APP->SPAT: Update self position
APP->SPAT: Update remote user positions 
end

group Spatial audio effect for media player
APP->SPAT: Update self position
APP->SPAT: Update player position
end

group Leave
APP->SPAT: Clear remote positions
APP->SPAT: Destroy the spatial audio engine 
APP->SDK: Leave the channel
APP->SDK: Destroy Agora engine
end

@enduml
