@startuml 
!include agora_skin.iuml
skinparam BoxPadding 30

actor "User" as USR

box "Your app"
participant "Video SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
participant "Spatial Audio\n Extension" as EXT
end box

APP -> API: AgoraRTC.createClient
group Setup the spatial audio extension
APP -> API: AgoraRTC.registerExtension
APP -> EXT: spatialAudioExtension.updateSelfPosition
end

USR -> APP: Join Channel
APP -> API: AgoraRTCClient.join

group Realize remote user's spatial audio
APP <- API: client.on("user-published")
APP -> API: AgoraRTCClient.subscribe
APP -> EXT: spatialAudioExtension.createProcessor
APP -> API: remoteTrack.pipe(processor).pipe(track.processorDestination)
APP -> API: remoteTrack.Play
APP -> EXT: processor.updateRemotePosition
end

group Spatial audio effect for media player
USR -> APP: Play media file
APP -> API: AgoraRTC.createBufferSourceAudioTrack
APP -> EXT: spatialAudioExtension.createProcessor
APP -> API: track.pipe(processor).pipe(track.processorDestination)
APP -> API: track.Play
APP -> EXT: processor.updatePlayerPositionInfo
end

group Cleanup
APP <- API: client.on("user-unpublished")
APP -> EXT: processor.removeRemotePosition

APP <- API: AgoraRTC.leave
APP -> EXT: processor.clearRemotePosition
end

@enduml
