@startuml 
!include agora_skin.iuml
skinparam BoxPadding 30

actor "User" as USR

box "Your client and server"
participant "Agora SDK" as APP
participant "Your Server" as SVR
end box

box "Agora"
participant "SD-RTN" as API
end box

USR -> APP: Enable spatial audio

group Spatial audio effects for users
APP -> SVR: Send local spatial position
APP <- SVR: Receive spatial position of remote user(s)

APP -> APP: Call update self position
APP -> APP: Call update remote position

APP -> API: Set remote user spatial audio parameters
end


group Spatial audio effects for media player
APP -> APP: Set spatial position of the user
APP -> APP: Set spatial position of the media player

APP -> API: Set spatial audio parameters
end

APP <-> API: Send and receive spatial audio

@enduml
