@startuml 
!include agora_skin.iuml
skinparam BoxPadding 30

actor "User" as USR

box "Your client and server"
participant "Agora SDK" as APP
participant "Your Server" as SVR

end box

box "Agora"
participant "SDRTN®" as API
participant "Local Spatial\nAudio Engine" as LSA
end box

USR -> APP: Enable spatial audio

group Initialize Local Spatial Audio Engine
APP -> LSA: Create local spatial audio engine
APP -> LSA: Initialize the engine
end

group Spatial audio effects for users
APP -> SVR: Send local spatial position
APP <- SVR: Receive spatial position of remote user(s)
APP -> LSA: Call update self position
APP -> LSA: Call update remote position
end


group Spatial audio effects for media player
APP -> LSA: Set spatial position of the user
APP -> LSA: Set spatial position of the media player
end

APP <-> API: Send and receive spatial audio

group Clean up
APP -> LSA: Clear remote positions
APP -> LSA: Destroy the spatial engine
end
@enduml
