@startuml 
!include agora_skin.iuml
skinparam BoxPadding 30

actor "User" as USR

box "Your app"
participant "Video SDK" as APP
end box

box "Agora"
participant "SD-RTN" as API
participant "Spatial Audio\n Extension" as EXT
end box

APP -> API: AgoraRTC.createClient
APP -> API: AgoraRTC.registerExtension

USR -> APP: Join Channel
APP -> API: AgoraRTCClient.join

USR -> APP: Play media file

group Spatial audio effect for media player
APP -> API: AgoraRTC.createBufferSourceAudioTrack
APP -> EXT: extension.createProcessor
APP -> API: track.pipe(processor).pipe(track.processorDestination)
APP -> API: track.Play
APP -> EXT: processor.updatePlayerPositionInfo
end

group Cleanup
APP <- API: AgoraRTC.leave
APP -> EXT: processor.clearRemotePosition
end

@enduml
