@startuml 
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Video SDK" as APP
end box

box "Agora"
participant "SD-RTN" as API
end box

group Start a task
USR -> APP: Start speech to text

APP -> API: Send an HTTP POST request to acquire a builderToken
APP <- API: Receive a builderToken in response

APP -> APP: Create JSON configuration for starting speech to text
APP -> API: Send an HTTP POST request containing the \nbuilderToken and JSON configuration to start a task
APP <- API: Receive the status and taskId in response
APP <- API: Receive the speech to text \ndata stream in a callback
USR <- APP: Display the text
end

group Query task status
APP -> API: Send an HTTP GET request containing \nthe taskId to query task status
APP <- API: Receive the current status in response
end

group Stop the task
USR -> APP: Stop speech to text
APP -> API: Send an HTTP DELETE request \ncontaining the taskId to stop the task
APP <- API: Receive a response confirming success
end

@enduml
