@startuml video-call-logic-web
!include agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open App
APP -> APP: Initiate the Video SDK engine:\n   agoraEngine = AgoraRTC.createClient
APP -> APP: Set the required event listners:\n agoraEngine.on("user-published") \n agoraEngine.on("user-unpublished")

group User
USR -> APP: Start call
APP->APP: Retrieve authentication token to join channel
APP -> API: Join a channel:\n agoraEngine.join
API -> APP : Join accepted
APP -> APP: Create local media tracks :\n AgoraRTC.createMicrophoneAudioTrack \n AgoraRTC.createCameraVideoTrack
APP -> API:  Push local media tracks to the channel:\n agoraEngine.publish
API -> APP: Retrieve streaming from the other user: \n agoraEngine.on("user-published")
API -> APP: Play remote media tracks: remoteVideoTrack.play \n remoteAudioTrack.play
API <-> APP: Receive and send data streams
end
USR -> APP: Leave call
APP -> API: leave the channel:\n agoraEngine.leave


@enduml
