@startuml 
!include agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Video SDK" as APP
end box

box "Agora"
participant "SD-RTN™" as API
end box

USR -> APP: Open App
APP -> APP: Setup app to handle local hardware and streaming.

group User
USR -> APP: Start call
APP -> APP: Create the agoraEngine\nconst agoraEngine = useRTCClient(AgoraRTC.createClient)
APP -> APP: Retrieve authentication token to join channel
APP -> API: Join a channel:\n useJoin
API -> APP : Join accepted
APP -> APP: Create local media tracks :\nconst { isLoading: isLoadingCam, localCameraTrack } = useLocalCameraTrack();\nconst { isLoading: isLoadingMic, localMicrophoneTrack } = useLocalMicroph
APP -> API:  Push local media tracks to the channel:\n usePublish([localMicrophoneTrack, localCameraTrack]);
API -> APP: Retrieve streaming from the other user: \n   <RemoteUser user={remoteUser} playVideo={true} playAudio={true} />
API <-> APP: Receive and send data streams
end

USR -> APP: Leave call
APP -> API: Leave the channel:\n useJoin

@enduml
