
@startuml

!include agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open app
APP -> APP: Initiate the Video SDK engine:\n  agoraEngine = AgoraRtcEngineKit.sharedEngine
APP -> APP: Setup the local video stream:\n  agoraEngine.enableVideo()
group Host
USR -> APP: Start a call
APP -> APP: In a call, all users send to the channel:\n agoraEngine.setClientRole(.broadcaster)
APP -> APP: Start local video:\n  agoraEngine.setupLocalVideo(videoCanvas)
APP -> API: Join the channel:\n agoraEngine?.joinChannel
APP -> API: Retrieve streaming from the other user: \n agoraEngine.setupRemoteVideo(videoCanvas)
API <-> APP: Receive and send data streams
end


USR -> APP: Leave the call
APP -> API: Stop local video:\n agoraEngine.stopPreview()
APP -> API: Leave the channel: \n agoraEngine.leaveChannel(nil)

USR -> APP: Close app
APP -> APP: Clean up local resources: \n AgoraRtcEngineKit.destroy()

@enduml
