@startuml
!include agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open game
APP -> APP: Initiate the Agora Video SDK engine: \n agoraEngine=IRtcEngine.GetEngine()
APP -> APP: Setup the local video stream:\n agoraEngine.EnableVideo()
APP -> APP: agoraEngine.EnableVideoObserver()

group User
USR -> APP: Start call
APP -> API: Join the channel: \n agoraEngine.JoinChannelByKey()
USR -> APP: Join call
API -> APP: A callback to start remote video: \n OnUserJoined()
APP -> API: Retrieve streaming from the other user: \n RemoteView.SetForUser(uid)
API <-> APP: Receive and send data stream
end

USR -> APP: Leave call
APP -> API: Leave the channel:\n agoraEngine.leaveChannel()
APP -> APP: Stop local video stream:\n agoraEngine.DisableVideo()
APP -> APP: Disable the video observer: \n agoraEngine.DisableVideoObserver()

USR -> APP: Close game
APP -> APP: Clean up local resources:\n  agoraEngine.destroy()


@enduml
