
@startuml

!include agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open app
APP -> APP: Initiate the Video SDK engine.
APP -> APP: Start video in the engine.
group Host
USR -> APP: Start call
APP -> APP: In a call, all users broadcast to the channel.
APP -> APP: Start local video.
APP -> API: Join the channel.
APP -> API: Retrieve streaming from the other user.
API <-> APP: Receive and send data streams
end


USR -> APP: Leave call
APP -> API: Stop local video.
APP -> API: Leave the channel.

USR -> APP: Close app
APP -> APP: Clean up local resources.

@enduml
