@startuml
!include agora_skin.iuml

participant "Your App Server" as APP

participant "Agora Cloud Recording" as CR

group Start recording
note left of APP: Acquire a resource ID
APP -> CR: 1. acquire
APP <-- CR: 2. Returns a resource ID
note left of APP: Start recording
APP -> CR: 3. start
APP <-- CR: 4. Returns a recording ID
end

group During the recording (Optional)
note left of APP: Query recording status
APP -> CR: 5. query
APP <-- CR: 6. Returns M3U8 filename and \ncurrent recording status
note left of APP: Update subscription lists
APP -> CR: 7. update
note left of APP: Update video layout
APP -> CR: 8. updateLayout
end

group Stop recording
APP -> CR: 9. stop
APP <-- CR: Returns M3U8 filename and \ncurrent uploading status
end


@enduml
