@startuml 
!include agora_skin.iuml
skinparam SequenceGroupBodyBackgroundColor transparent

actor "User" as USR

box "Your app"
participant "Media Accelerator\n SDK" as APP
end box

box "Agora"
participant "SD-RTN" as API
end box

group Setup Agora RTC service
APP -> APP: Instantiate the Agora RTC service object
APP -> APP: Set service options
APP -> API: Verify license and initialize the service
APP -> API: Create connection-1 
APP -> API: Create connection-2
end

group Stream to multiple channels
USR -> APP: Join channels
APP -> API: Join channel-1 using connectionId-1
APP -> API: Join channel-2 using connectionId-2
APP -> API: Send audio and video data using \nconnectionId-1 to stream to channel-1
APP -> API: Send audio and video data using \nconnectionId-2 to stream to channel-2
end

group Push multiple streams to a single channel
USR -> APP: Join channel
APP -> API: Join channel-1 using \nconnectionId-1 and userId-1
APP -> API: Join channel-1 using \nconnectionId-2 and userId-2
APP -> API: Send audio and video data using \nconnectionId-1 to send stream-1
APP -> API: Send audio and video data using \nconnectionId-2 to send stream-2
end

group Leave channel(s)
USR -> APP: Leave channel(s)
APP -> API: Leave all channel(s)\n using the associated connectionIds
end

group Clean up
APP -> API: Destroy connection-1 \nusing connectionId-1
APP -> API: Destroy connection-2 \nusing connectionId-2
APP -> API: Call the finish method to release resources
end

@enduml
