@startuml 
!include agora_skin.iuml
skinparam SequenceGroupBodyBackgroundColor transparent

actor "User" as USR

box "Your app"
participant "Media Accelerator\n SDK" as APP
end box

box "Agora"
participant "SD-RTN" as API
end box

group Verify license
USR -> APP: Start device
APP -> APP: Get the device credential
APP -> API: Call the method to verify device license
end

group Setup Agora RTC service
APP -> APP: Instantiate the Agora RTC service
APP -> APP: Set service options
APP -> APP: Initialize the service
end

group Join a channel
USR -> APP: Join a channel
APP -> APP: Create a connection
APP -> API: Call the method to Join a channel
APP <- API: on join channel success callback
end

group Send audio and video
APP -> API: Send audio data
APP -> API: Send video data
end

group Receive audio and video
APP <- API: on audio data call back
APP -> USR: Render audio
APP <- API: on video data call back
APP -> USR: Render video
end

group Leave channel
USR -> APP: Leave channel
APP -> API: Call the leave channel method
end

group Clean up
APP -> API: Call the fini() method to release resources
APP -> API: Destroy the connection
end

@enduml
