@startuml 
!include agora_skin.iuml
skinparam SequenceGroupBodyBackgroundColor transparent

actor "User" as USR

box "Your app"
participant "Media Accelerator\n SDK" as APP
end box

box "Agora"
participant "SD-RTN" as API
end box

group Setup Agora RTC service
APP -> APP: Instantiate the Agora RTC service object
APP -> APP: Set service options
APP -> API: Verify license and initialize the service
APP -> API: Create a connection
end

group Join a channel
USR -> APP: Join a channel
APP -> API: Call the method to Join a channel
APP <- API: on join channel success callback
end

group Send audio and video
APP -> API: Start thread to send audio data
APP -> API: Start thread to send video data
end

group Receive audio and video
APP <- API: on audio data callback
APP -> USR: Render audio frame
APP <- API: on video data callback
APP -> USR: Render video frame
end

group Leave channel
USR -> APP: Leave channel
APP -> API: Call the leave channel method
end

group Clean up
APP -> API: Destroy the connection
APP -> API: Call the finish method to release resources
end

@enduml
