@startuml 
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Implemented by you"
participant "Web server" as SVR
participant "Your app server" as APP
participant "Your\nthird-party\ncloud storage" as CLD
end box

box "Provided by Agora"
participant "Agora\nCloud Recording" as ACR
end box
USR -> APP: Start recording
APP -> ACR: Get recording resources
APP <- ACR: resource ID
APP -> ACR: Start recording
ACR -> SVR: Notification 40: `recorder_started` <status>
SVR -> ACR: 200 OK
note over CLD: Notifications sent and acknowledged for all recording events
USR -> APP: Stop recording
APP -> ACR: End recording

ACR -> SVR: Notification 30: `uploader_started` <status>
SVR -> ACR: 200 OK
ACR -> CLD: Upload recording file
ACR -> SVR: Notification 31: `uploaded` <status>
SVR -> ACR: 200 OK

ACR -> SVR: Notification 11: `session_exit` <exitStatus>
SVR -> ACR: 200 OK

@enduml
