@startuml 
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Implemented by you"
participant "Web server" as SVR
participant "Your app server" as APP
end box

box "Provided by Agora"
participant "Agora\nMedia Pull" as AMP
end box
USR -> APP: Start pulling media \ninto an Agora channel
APP -> AMP: Create player API
APP <- AMP: Response containing player parameters
AMP -> SVR: Notification eventType=1: Player created
SVR -> SVR: Authenticate notification signature
SVR -> AMP: 200 OK

USR -> APP: Change player status
APP -> AMP: Update player API
APP <- AMP: Response containing player parameters
AMP -> SVR: Notification eventType=4: Player status changed
SVR -> SVR: Authenticate notification signature
SVR -> AMP: 200 OK

USR -> APP: Stop playing media
APP -> AMP: Delete player API
APP <- AMP: Response confirming player delete
AMP -> SVR: Notification eventType=2: Player destroyed
SVR -> SVR: Authenticate notification signature
SVR -> AMP: 200 OK


@enduml
