@startuml 
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Implemented by you"
participant "Web server" as SVR
participant "Your app server" as APP
end box

box "Provided by Agora"
participant "Agora\nMedia Push" as AMP
end box
USR -> APP: Start media push
APP -> AMP: Create a converter
APP <- AMP: Response confirming conveter creation
AMP -> SVR: Notification eventType=1: Converter created
SVR -> SVR: Authenticate notification signature
SVR -> AMP: 200 OK

USR -> APP: Change converter configuration
APP -> AMP: Update converter API
APP <- AMP: Response confirming configuration update
AMP -> SVR: Notification eventType=2: Converter configuration changed
SVR -> SVR: Authenticate notification signature
SVR -> AMP: 200 OK

AMP -> SVR: Notification eventType=3: Converter status changed
SVR -> SVR: Authenticate notification signature
SVR -> AMP: 200 OK

USR -> APP: Stop media push
APP -> AMP: Delete converter API
APP <- AMP: Response confirming converter delete
AMP -> SVR: Notification eventType=4: Converter destroyed
SVR -> SVR: Authenticate notification signature
SVR -> AMP: 200 OK

@enduml
