@startuml
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Implemented by you"
participant "Web server" as SVR
participant "App" as APP
end box

box "Provided by Agora"
participant "SD-RTN" as API
end box

box "Provided by ActiveFence"
participant "ActiveFence" as AF
end box

USR -> APP: Login
APP <-> API: Login authentication

USR -> APP: Join channel
APP -> API: Join channel with \n ActiveFence activated
API <-> AF: Monitor content \nin channel
AF -> AF: Content matches\n workflow risk
AF -> SVR: Action webhook
SVR -> API: Act on webhook. For example, use\n Channel Management REST API\n to remove user from channel
API -> APP: Log user out
APP -> USR: Logout


@enduml
