@startuml
!include ../video-sdk/agora_skin.iuml

[AI Noise suppression]

package "Audio and video data"  {
  [Capture] - [Pre-process]
  [Pre-process] - [Encode]
  [Encode] - [Transmit]
  [Transmit] - [Decode]
  [Decode] - [Post-process]
  [Post-process] - [Play]
}

  [Pre-process] <-up--> [AI Noise suppression] : "  Audio data  "

@enduml