@startuml
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Implemented by you"
participant "Web server" as WS
participant "App" as APP
end box

box "Agora"
participant "SDRTN<sup>®</sup>" as SDRTN
end box

box "Provided by ActiveFence"
participant "ActiveFence" as AF
end box

USR -> APP: Login
APP <-> SDRTN: Login authentication
USR -> APP: Join channel
APP -> SDRTN: Join channel with\nActiveFence activated
SDRTN <-> AF: Monitor content\nin channel
AF -> AF: Content matches\nworkflow risk
AF -> WS: Action webhook
WS -> SDRTN: Act on webhook. For example, use\nChannel Management REST API\nto remove user from channel
SDRTN -> APP: Log user out
APP -> USR: Logout
@enduml