@startuml
!include ../video-sdk/agora_skin.iuml

actor "User" as USR

box "Your app"
participant "Video SDK" as APP
end box

box "Agora"
participant "SDRTN®" as API
end box

USR -> APP: Open App
APP -> APP: Create an instance of Agora Engine using Video SDK
APP -> APP: Enable audio and video in Agora Engine

group Setup raw data processing
APP -> APP: Setup the audio frame observer 
APP -> APP: Setup the video frame observer 
end

group Join
USR -> APP: Join a channel
APP -> API: Register the video frame observer
APP -> API: Register the audio frame observer
APP -> API: Set audio frame parameters
APP -> APP: Retrieve authentication token to join a channel
APP -> API: Join the channel 
end

group Process raw audio and video data
APP <- API: Get the raw data in the callbacks
APP -> API: Send the processed data back with the callbacks
end

group Leave
USR -> APP: Leave the channel
APP -> API: Unegister the video frame observer
APP -> API: Unegister the audio frame observer
APP -> API: Leave the channel
end

@enduml
