@startuml video-call-logic-flutter
!include agora_skin.iuml

actor "User" as USR

box "Your app"

participant "Video SDK" as APP

end box

box "Agora"

participant "SD-RTN" as API

end box

USR -> APP: Open App
APP -> APP: Initiate the Agora Video SDK engine: \n agoraEngine = RtcEngine.create
APP -> APP: Setup the local video stream: \n  agoraEngine.enableVideo
APP -> APP: Widget = RtcLocalView.SurfaceView()

group User
USR -> APP: Join a call
APP->APP: Retrieve authentication token to join channel
APP -> API: Join the channel:\n agoraEngine.joinChannel
APP -> API: Retrieve streaming from the other user: \nWidget = RtcRemoteView.SurfaceView()
API <-> APP: Receive and send data stream

end

USR -> APP: Leave call
APP -> API: Leave the channel\n agoraEngine.leaveChannel
USR -> APP: Close app
APP -> APP: Clean up local resources: \n  agoraEngine.destroy()

@enduml