@startuml
!include agora_skin.iuml

box "Call implementer"
participant "Client" as AC
participant "Token Server" as TS
participant "Client" as AC2
end box


box "Agora"
participant "Agora Platform" as AP
end box


group Setup client

AC -> AC: User login to implementor security
AC <-> TS: Authenticate and retrieve token
AC2 -> AC2: User login to implementor security
AC2 <-> TS: Authenticate and retrieve token
AC -> AC: Create client instance
AC -> AC: Set client role: host

AC2 -> AC2: Create  client instance
AC2 -> AC2: Set client role: audience

end

group Run call
AC -> AC: Connect to local audio and video resources
AC -> AP: Join channel
AC -> AP: Send audio and video to channel

AC2 -> AP: Join channel
AP -> AC2: Send audio and video to channel

AC <-> AC2: Communicate
end

group End call

AC2 -> AC2: Close audio and video
AC2 -> AP: Leave call

AC -> AC: Close audio and video
AC -> AP: Leave call

end


@enduml